from dataclasses import dataclass


@dataclass(frozen=True)
class AliyunOperation:
    name: str
    action: str
    version: str
    resource_type: str
    result_path: tuple
    method: str = "POST"
    parameters: dict = None
    pagination: str = "page"  # page, marker, token, none
    page_size: int = 50
    token_param: str = "NextToken"
    limit_param: str = "MaxResults"
    page_number_param: str = "PageNumber"
    page_size_param: str = "PageSize"
    iterate_from: str = None
    iterate_param: str = None
    iterate_field: str = None
    iterate_params: dict = None


@dataclass(frozen=True)
class AliyunServiceSpec:
    endpoint_template: str
    regional: bool = True


SERVICE_SPECS = {
    "ecs": AliyunServiceSpec(endpoint_template="ecs.{region}.aliyuncs.com"),
    "vpc": AliyunServiceSpec(endpoint_template="vpc.{region}.aliyuncs.com"),
    "slb": AliyunServiceSpec(endpoint_template="slb.{region}.aliyuncs.com"),
    "rds": AliyunServiceSpec(endpoint_template="rds.{region}.aliyuncs.com"),
    "ram": AliyunServiceSpec(endpoint_template="ram.aliyuncs.com", regional=False),
    "nas": AliyunServiceSpec(endpoint_template="nas.{region}.aliyuncs.com"),
    "oss": AliyunServiceSpec(endpoint_template="oss-{region}.aliyuncs.com"),
    "alb": AliyunServiceSpec(endpoint_template="alb.{region}.aliyuncs.com"),
    "cdn": AliyunServiceSpec(endpoint_template="cdn.aliyuncs.com", regional=False),
    "actiontrail": AliyunServiceSpec(endpoint_template="actiontrail.{region}.aliyuncs.com"),
    "ebs": AliyunServiceSpec(endpoint_template="ebs.{region}.aliyuncs.com"),
    "eci": AliyunServiceSpec(endpoint_template="eci.{region}.aliyuncs.com"),
    "ros": AliyunServiceSpec(endpoint_template="ros.aliyuncs.com", regional=False),
    "drds": AliyunServiceSpec(endpoint_template="drds.{region}.aliyuncs.com"),
    "domain": AliyunServiceSpec(endpoint_template="domain.aliyuncs.com", regional=False),
    "elasticsearch": AliyunServiceSpec(endpoint_template="elasticsearch.{region}.aliyuncs.com"),
    "alidns": AliyunServiceSpec(endpoint_template="alidns.aliyuncs.com", regional=False),
    "kms": AliyunServiceSpec(endpoint_template="kms.{region}.aliyuncs.com"),
    "ocr": AliyunServiceSpec(endpoint_template="ocr.{region}.aliyuncs.com"),
    "polardb": AliyunServiceSpec(endpoint_template="polardb.{region}.aliyuncs.com"),
    "privatelink": AliyunServiceSpec(endpoint_template="privatelink.{region}.aliyuncs.com"),
    "sts": AliyunServiceSpec(endpoint_template="sts.aliyuncs.com", regional=False),
    "vpcpeer": AliyunServiceSpec(endpoint_template="vpc.{region}.aliyuncs.com"),
    "dbs": AliyunServiceSpec(endpoint_template="dbs.{region}.aliyuncs.com"),
    "das": AliyunServiceSpec(endpoint_template="das.{region}.aliyuncs.com"),
    "dds": AliyunServiceSpec(endpoint_template="dds.{region}.aliyuncs.com"),
    "alikafka": AliyunServiceSpec(endpoint_template="alikafka.{region}.aliyuncs.com"),
    "mts": AliyunServiceSpec(endpoint_template="mts.{region}.aliyuncs.com"),
    "cloud-siem": AliyunServiceSpec(endpoint_template="cloud-siem.{region}.aliyuncs.com"),
    "arms": AliyunServiceSpec(endpoint_template="arms.{region}.aliyuncs.com"),
    "adb": AliyunServiceSpec(endpoint_template="adb.{region}.aliyuncs.com"),
    "cr": AliyunServiceSpec(endpoint_template="cr.{region}.aliyuncs.com"),
    "dms-enterprise": AliyunServiceSpec(endpoint_template="dms-enterprise.{region}.aliyuncs.com"),
}


ALIYUN_OPERATIONS = {
    "ecs": [
        AliyunOperation(
            name="DescribeInstances",
            action="DescribeInstances",
            version="2014-05-26",
            resource_type="Instances",
            result_path=("Instances", "Instance"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeDisks",
            action="DescribeDisks",
            version="2014-05-26",
            resource_type="Disks",
            result_path=("Disks", "Disk"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeSecurityGroups",
            action="DescribeSecurityGroups",
            version="2014-05-26",
            resource_type="SecurityGroups",
            result_path=("SecurityGroups", "SecurityGroup"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeSnapshots",
            action="DescribeSnapshots",
            version="2014-05-26",
            resource_type="Snapshots",
            result_path=("Snapshots", "Snapshot"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeImages",
            action="DescribeImages",
            version="2014-05-26",
            resource_type="Images",
            result_path=("Images", "Image"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeInstanceStatus",
            action="DescribeInstanceStatus",
            version="2014-05-26",
            resource_type="InstanceStatuses",
            result_path=("InstanceStatuses", "InstanceStatus"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeNetworkInterfaces",
            action="DescribeNetworkInterfaces",
            version="2014-05-26",
            resource_type="NetworkInterfaces",
            result_path=("NetworkInterfaceSets", "NetworkInterfaceSet"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeKeyPairs",
            action="DescribeKeyPairs",
            version="2014-05-26",
            resource_type="KeyPairs",
            result_path=("KeyPairs", "KeyPair"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeZones",
            action="DescribeZones",
            version="2014-05-26",
            resource_type="Zones",
            result_path=("Zones", "Zone"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeInstanceTypes",
            action="DescribeInstanceTypes",
            version="2014-05-26",
            resource_type="InstanceTypes",
            result_path=("InstanceTypes", "InstanceType"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeInstanceTypeFamilies",
            action="DescribeInstanceTypeFamilies",
            version="2014-05-26",
            resource_type="InstanceTypeFamilies",
            result_path=("InstanceTypeFamilies", "InstanceTypeFamily"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeInstanceAttribute",
            action="DescribeInstanceAttribute",
            version="2014-05-26",
            resource_type="InstanceAttribute",
            result_path=("Instance",),
            pagination="none",
            iterate_from="DescribeInstances",
            iterate_params={"InstanceId": "InstanceId"},
        ),
        AliyunOperation(
            name="DescribeSecurityGroupAttribute",
            action="DescribeSecurityGroupAttribute",
            version="2014-05-26",
            resource_type="SecurityGroupAttribute",
            result_path=("Permissions", "Permission"),
            pagination="none",
            iterate_from="DescribeSecurityGroups",
            iterate_params={"SecurityGroupId": "SecurityGroupId"},
        ),
        AliyunOperation(
            name="DescribeDiskAttribute",
            action="DescribeDiskAttribute",
            version="2014-05-26",
            resource_type="DiskAttribute",
            result_path=("Disk",),
            pagination="none",
            iterate_from="DescribeDisks",
            iterate_params={"DiskId": "DiskId"},
        ),
        AliyunOperation(
            name="DescribeSnapshotAttribute",
            action="DescribeSnapshotAttribute",
            version="2014-05-26",
            resource_type="SnapshotAttribute",
            result_path=("Snapshot",),
            pagination="none",
            iterate_from="DescribeSnapshots",
            iterate_params={"SnapshotId": "SnapshotId"},
        ),
        AliyunOperation(
            name="DescribeNetworkInterfaceAttribute",
            action="DescribeNetworkInterfaceAttribute",
            version="2014-05-26",
            resource_type="NetworkInterfaceAttribute",
            result_path=("NetworkInterfaceSet",),
            pagination="none",
            iterate_from="DescribeNetworkInterfaces",
            iterate_params={"NetworkInterfaceId": "NetworkInterfaceId"},
        ),
    ],
    "vpc": [
        AliyunOperation(
            name="DescribeVpcs",
            action="DescribeVpcs",
            version="2016-04-28",
            resource_type="Vpcs",
            result_path=("Vpcs", "Vpc"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeVSwitches",
            action="DescribeVSwitches",
            version="2016-04-28",
            resource_type="VSwitches",
            result_path=("VSwitches", "VSwitch"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeEipAddresses",
            action="DescribeEipAddresses",
            version="2016-04-28",
            resource_type="EipAddresses",
            result_path=("EipAddresses", "EipAddress"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeNatGateways",
            action="DescribeNatGateways",
            version="2016-04-28",
            resource_type="NatGateways",
            result_path=("NatGateways", "NatGateway"),
            page_size=50,
        ),
    ],
    "slb": [
        AliyunOperation(
            name="DescribeLoadBalancers",
            action="DescribeLoadBalancers",
            version="2014-05-15",
            resource_type="LoadBalancers",
            result_path=("LoadBalancers", "LoadBalancer"),
            page_size=50,
        ),
    ],
    "rds": [
        AliyunOperation(
            name="DescribeDBInstances",
            action="DescribeDBInstances",
            version="2014-08-15",
            resource_type="DBInstances",
            result_path=("Items", "DBInstance"),
            page_size=30,
        ),
        AliyunOperation(
            name="DescribeBackups",
            action="DescribeBackups",
            version="2014-08-15",
            resource_type="Backups",
            result_path=("Items", "Backup"),
            page_size=30,
            parameters={"StartTime": "__DEFAULT_START_TIME__", "EndTime": "__DEFAULT_END_TIME__"},
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
        AliyunOperation(
            name="DescribeBackupTasks",
            action="DescribeBackupTasks",
            version="2014-08-15",
            resource_type="BackupTasks",
            result_path=("Items", "BackupTask"),
            page_size=30,
            parameters={"StartTime": "__DEFAULT_START_TIME__", "EndTime": "__DEFAULT_END_TIME__"},
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
        AliyunOperation(
            name="DescribeLogBackupFiles",
            action="DescribeLogBackupFiles",
            version="2014-08-15",
            resource_type="LogBackupFiles",
            result_path=("Items", "LogBackupFile"),
            page_size=30,
            parameters={"StartTime": "__DEFAULT_START_TIME__", "EndTime": "__DEFAULT_END_TIME__"},
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
        AliyunOperation(
            name="DescribeBinlogFiles",
            action="DescribeBinlogFiles",
            version="2014-08-15",
            resource_type="BinlogFiles",
            result_path=("Items", "BinlogFile"),
            page_size=30,
            parameters={"StartTime": "__DEFAULT_START_TIME__", "EndTime": "__DEFAULT_END_TIME__"},
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
        AliyunOperation(
            name="DescribeErrorLogs",
            action="DescribeErrorLogs",
            version="2014-08-15",
            resource_type="ErrorLogs",
            result_path=("Items", "Log"),
            page_size=30,
            parameters={"StartTime": "__DEFAULT_START_TIME__", "EndTime": "__DEFAULT_END_TIME__"},
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
        AliyunOperation(
            name="DescribeSlowLogs",
            action="DescribeSlowLogs",
            version="2014-08-15",
            resource_type="SlowLogs",
            result_path=("Items", "SQLSlowRecord"),
            page_size=30,
            parameters={"StartTime": "__DEFAULT_START_TIME__", "EndTime": "__DEFAULT_END_TIME__"},
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
        AliyunOperation(
            name="DescribeSlowLogRecords",
            action="DescribeSlowLogRecords",
            version="2014-08-15",
            resource_type="SlowLogRecords",
            result_path=("Items", "SQLSlowRecord"),
            page_size=30,
            parameters={"StartTime": "__DEFAULT_START_TIME__", "EndTime": "__DEFAULT_END_TIME__"},
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
        AliyunOperation(
            name="DescribeSQLLogRecords",
            action="DescribeSQLLogRecords",
            version="2014-08-15",
            resource_type="SQLLogRecords",
            result_path=("Items", "SQLRecord"),
            page_size=30,
            parameters={"StartTime": "__DEFAULT_START_TIME__", "EndTime": "__DEFAULT_END_TIME__"},
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
        AliyunOperation(
            name="DescribeSQLLogFiles",
            action="DescribeSQLLogFiles",
            version="2014-08-15",
            resource_type="SQLLogFiles",
            result_path=("Items", "SQLLogFile"),
            page_size=30,
            parameters={"StartTime": "__DEFAULT_START_TIME__", "EndTime": "__DEFAULT_END_TIME__"},
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
        AliyunOperation(
            name="DescribeSQLLogReportList",
            action="DescribeSQLLogReportList",
            version="2014-08-15",
            resource_type="SQLLogReports",
            result_path=("Items", "Report"),
            page_size=30,
            parameters={"StartTime": "__DEFAULT_START_TIME__", "EndTime": "__DEFAULT_END_TIME__"},
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
        AliyunOperation(
            name="DescribeEvents",
            action="DescribeEvents",
            version="2014-08-15",
            resource_type="Events",
            result_path=("Items", "Event"),
            page_size=30,
            parameters={"StartTime": "__DEFAULT_START_TIME__", "EndTime": "__DEFAULT_END_TIME__"},
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
        AliyunOperation(
            name="DescribeHistoryEvents",
            action="DescribeHistoryEvents",
            version="2014-08-15",
            resource_type="HistoryEvents",
            result_path=("Items", "Event"),
            page_size=30,
            parameters={"StartTime": "__DEFAULT_START_TIME__", "EndTime": "__DEFAULT_END_TIME__"},
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
        AliyunOperation(
            name="DescribeHistoryTasks",
            action="DescribeHistoryTasks",
            version="2014-08-15",
            resource_type="HistoryTasks",
            result_path=("Items", "Task"),
            page_size=30,
            parameters={"StartTime": "__DEFAULT_START_TIME__", "EndTime": "__DEFAULT_END_TIME__"},
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
        AliyunOperation(
            name="DescribeHistoryEventsStat",
            action="DescribeHistoryEventsStat",
            version="2014-08-15",
            resource_type="HistoryEventsStat",
            result_path=("Items", "Event"),
            page_size=30,
            parameters={"StartTime": "__DEFAULT_START_TIME__", "EndTime": "__DEFAULT_END_TIME__"},
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
        AliyunOperation(
            name="DescribeHistoryTasksStat",
            action="DescribeHistoryTasksStat",
            version="2014-08-15",
            resource_type="HistoryTasksStat",
            result_path=("Items", "Task"),
            page_size=30,
            parameters={"StartTime": "__DEFAULT_START_TIME__", "EndTime": "__DEFAULT_END_TIME__"},
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
        AliyunOperation(
            name="DescribeDatabases",
            action="DescribeDatabases",
            version="2014-08-15",
            resource_type="Databases",
            result_path=("Databases", "Database"),
            page_size=30,
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
        AliyunOperation(
            name="DescribeDBInstanceAttribute",
            action="DescribeDBInstanceAttribute",
            version="2014-08-15",
            resource_type="DBInstanceAttributes",
            result_path=("Items", "DBInstanceAttribute"),
            pagination="none",
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
        AliyunOperation(
            name="DescribeAccounts",
            action="DescribeAccounts",
            version="2014-08-15",
            resource_type="DBAccounts",
            result_path=("Accounts", "DBInstanceAccount"),
            pagination="none",
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
        AliyunOperation(
            name="DescribeDBInstanceIPs",
            action="DescribeDBInstanceIPs",
            version="2014-08-15",
            resource_type="DBInstanceIPs",
            result_path=("Items", "DBInstanceIP"),
            pagination="none",
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
    ],
    "alb": [
        AliyunOperation(
            name="ListLoadBalancers",
            action="ListLoadBalancers",
            version="2020-06-16",
            resource_type="LoadBalancers",
            result_path=("LoadBalancers",),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
        ),
        AliyunOperation(
            name="ListListeners",
            action="ListListeners",
            version="2020-06-16",
            resource_type="Listeners",
            result_path=("Listeners",),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
            iterate_from="ListLoadBalancers",
            iterate_params={"LoadBalancerIds.1": "LoadBalancerId"},
        ),
        AliyunOperation(
            name="ListRules",
            action="ListRules",
            version="2020-06-16",
            resource_type="Rules",
            result_path=("Rules",),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
            iterate_from="ListListeners",
            iterate_params={"ListenerIds.1": "ListenerId"},
        ),
        AliyunOperation(
            name="ListServerGroups",
            action="ListServerGroups",
            version="2020-06-16",
            resource_type="ServerGroups",
            result_path=("ServerGroups",),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
            iterate_from="ListLoadBalancers",
            iterate_params={"LoadBalancerIds.1": "LoadBalancerId"},
        ),
        AliyunOperation(
            name="ListServerGroupServers",
            action="ListServerGroupServers",
            version="2020-06-16",
            resource_type="ServerGroupServers",
            result_path=("Servers", "Server"),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
            iterate_from="ListServerGroups",
            iterate_params={"ServerGroupId": "ServerGroupId"},
        ),
        AliyunOperation(
            name="ListSecurityPolicies",
            action="ListSecurityPolicies",
            version="2020-06-16",
            resource_type="SecurityPolicies",
            result_path=("SecurityPolicies",),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
        ),
        AliyunOperation(
            name="ListSecurityPolicyRelations",
            action="ListSecurityPolicyRelations",
            version="2020-06-16",
            resource_type="SecurityPolicyRelations",
            result_path=("SecurityPolicyRelations",),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
            iterate_from="ListSecurityPolicies",
            iterate_params={"SecurityPolicyIds.1": "SecurityPolicyId"},
        ),
        AliyunOperation(
            name="ListSystemSecurityPolicies",
            action="ListSystemSecurityPolicies",
            version="2020-06-16",
            resource_type="SystemSecurityPolicies",
            result_path=("SystemSecurityPolicies",),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
        ),
        AliyunOperation(
            name="ListListenerCertificates",
            action="ListListenerCertificates",
            version="2020-06-16",
            resource_type="ListenerCertificates",
            result_path=("Certificates", "Certificate"),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
            iterate_from="ListListeners",
            iterate_params={"ListenerId": "ListenerId"},
        ),
        AliyunOperation(
            name="ListTagKeys",
            action="ListTagKeys",
            version="2020-06-16",
            resource_type="TagKeys",
            result_path=("TagKeys",),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
        ),
        AliyunOperation(
            name="ListTagValues",
            action="ListTagValues",
            version="2020-06-16",
            resource_type="TagValues",
            result_path=("TagValues",),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
        ),
        AliyunOperation(
            name="ListTagResources",
            action="ListTagResources",
            version="2020-06-16",
            resource_type="TagResources",
            result_path=("TagResources", "TagResource"),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
            iterate_from="ListLoadBalancers",
            iterate_params={"ResourceId.1": "LoadBalancerId", "ResourceType": "LoadBalancer"},
        ),
    ],
    "cdn": [
        AliyunOperation(
            name="DescribeUserDomains",
            action="DescribeUserDomains",
            version="2018-05-10",
            resource_type="Domains",
            result_path=("Domains", "PageData"),
            page_size=50,
        ),
    ],
    "ram": [
        AliyunOperation(
            name="ListUsers",
            action="ListUsers",
            version="2015-05-01",
            resource_type="Users",
            result_path=("Users", "User"),
            pagination="marker",
            page_size=100,
        ),
        AliyunOperation(
            name="ListAccessKeys",
            action="ListAccessKeys",
            version="2015-05-01",
            resource_type="AccessKeys",
            result_path=("AccessKeys", "AccessKey"),
            pagination="marker",
            page_size=100,
            iterate_from="ListUsers",
            iterate_params={"UserName": "UserName"},
        ),
        AliyunOperation(
            name="ListRoles",
            action="ListRoles",
            version="2015-05-01",
            resource_type="Roles",
            result_path=("Roles", "Role"),
            pagination="marker",
            page_size=100,
        ),
        AliyunOperation(
            name="ListPolicies",
            action="ListPolicies",
            version="2015-05-01",
            resource_type="Policies",
            result_path=("Policies", "Policy"),
            pagination="marker",
            page_size=100,
        ),
        AliyunOperation(
            name="ListPolicyVersions",
            action="ListPolicyVersions",
            version="2015-05-01",
            resource_type="PolicyVersions",
            result_path=("PolicyVersions", "PolicyVersion"),
            pagination="marker",
            page_size=100,
            iterate_from="ListPolicies",
            iterate_params={"PolicyName": "PolicyName", "PolicyType": "PolicyType"},
        ),
        AliyunOperation(
            name="ListGroups",
            action="ListGroups",
            version="2015-05-01",
            resource_type="Groups",
            result_path=("Groups", "Group"),
            pagination="marker",
            page_size=100,
        ),
        AliyunOperation(
            name="ListEntitiesForPolicy",
            action="ListEntitiesForPolicy",
            version="2015-05-01",
            resource_type="EntitiesForPolicy",
            result_path=("PolicyGroups",),
            pagination="marker",
            page_size=100,
            iterate_from="ListPolicies",
            iterate_params={"PolicyName": "PolicyName", "PolicyType": "PolicyType"},
        ),
        AliyunOperation(
            name="ListGroupsForUser",
            action="ListGroupsForUser",
            version="2015-05-01",
            resource_type="GroupsForUser",
            result_path=("Groups", "Group"),
            pagination="marker",
            page_size=100,
            iterate_from="ListUsers",
            iterate_params={"UserName": "UserName"},
        ),
        AliyunOperation(
            name="ListPoliciesForGroup",
            action="ListPoliciesForGroup",
            version="2015-05-01",
            resource_type="PoliciesForGroup",
            result_path=("Policies", "Policy"),
            pagination="marker",
            page_size=100,
            iterate_from="ListGroups",
            iterate_params={"GroupName": "GroupName"},
        ),
        AliyunOperation(
            name="ListPoliciesForRole",
            action="ListPoliciesForRole",
            version="2015-05-01",
            resource_type="PoliciesForRole",
            result_path=("Policies", "Policy"),
            pagination="marker",
            page_size=100,
            iterate_from="ListRoles",
            iterate_params={"RoleName": "RoleName"},
        ),
        AliyunOperation(
            name="ListPoliciesForUser",
            action="ListPoliciesForUser",
            version="2015-05-01",
            resource_type="PoliciesForUser",
            result_path=("Policies", "Policy"),
            pagination="marker",
            page_size=100,
            iterate_from="ListUsers",
            iterate_params={"UserName": "UserName"},
        ),
        AliyunOperation(
            name="ListUsersForGroup",
            action="ListUsersForGroup",
            version="2015-05-01",
            resource_type="UsersForGroup",
            result_path=("Users", "User"),
            pagination="marker",
            page_size=100,
            iterate_from="ListGroups",
            iterate_params={"GroupName": "GroupName"},
        ),
        AliyunOperation(
            name="ListVirtualMFADevices",
            action="ListVirtualMFADevices",
            version="2015-05-01",
            resource_type="VirtualMFADevices",
            result_path=("VirtualMFADevices", "VirtualMFADevice"),
            pagination="marker",
            page_size=100,
        ),
    ],
    "nas": [
        AliyunOperation(
            name="DescribeFileSystems",
            action="DescribeFileSystems",
            version="2017-06-26",
            resource_type="FileSystems",
            result_path=("FileSystems", "FileSystem"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeMountTargets",
            action="DescribeMountTargets",
            version="2017-06-26",
            resource_type="MountTargets",
            result_path=("MountTargets", "MountTarget"),
            page_size=50,
        ),
    ],
    "oss": [
        AliyunOperation(
            name="ListBuckets",
            action="ListBuckets",
            version="2013-10-15",
            resource_type="Buckets",
            result_path=("Buckets",),
            pagination="none",
        ),
    ],
    "drds": [
        AliyunOperation(
            name="DescribeDrdsInstances",
            action="DescribeDrdsInstances",
            version="2019-01-23",
            resource_type="DrdsInstances",
            result_path=("DrdsInstances", "DrdsInstance"),
            page_size=50,
        ),
    ],
    "domain": [
        AliyunOperation(
            name="QueryDomainList",
            action="QueryDomainList",
            version="2018-01-29",
            resource_type="Domains",
            result_path=("Data", "Domain"),
            page_size=50,
            page_number_param="PageNum",
        ),
    ],
    "elasticsearch": [
        AliyunOperation(
            name="ListInstance",
            action="ListInstance",
            version="2017-06-13",
            resource_type="Instances",
            result_path=("Result", "Instance"),
            page_size=20,
        ),
    ],
    "alidns": [
        AliyunOperation(
            name="DescribeDomains",
            action="DescribeDomains",
            version="2015-01-09",
            resource_type="Domains",
            result_path=("Domains", "Domain"),
            page_size=100,
        ),
        AliyunOperation(
            name="DescribeDomainGroups",
            action="DescribeDomainGroups",
            version="2015-01-09",
            resource_type="DomainGroups",
            result_path=("DomainGroups", "DomainGroup"),
            page_size=100,
        ),
        AliyunOperation(
            name="DescribeSupportLines",
            action="DescribeSupportLines",
            version="2015-01-09",
            resource_type="SupportLines",
            result_path=("RecordLines", "RecordLine"),
            pagination="none",
        ),
        AliyunOperation(
            name="DescribeCustomLines",
            action="DescribeCustomLines",
            version="2015-01-09",
            resource_type="CustomLines",
            result_path=("CustomLines", "CustomLine"),
            page_size=100,
        ),
        AliyunOperation(
            name="DescribeDnsCacheDomains",
            action="DescribeDnsCacheDomains",
            version="2015-01-09",
            resource_type="DnsCacheDomains",
            result_path=("Domains", "Domain"),
            page_size=100,
        ),
        AliyunOperation(
            name="DescribeTags",
            action="DescribeTags",
            version="2015-01-09",
            resource_type="Tags",
            result_path=("Tags", "Tag"),
            page_size=100,
        ),
        AliyunOperation(
            name="DescribeDomainInfo",
            action="DescribeDomainInfo",
            version="2015-01-09",
            resource_type="DomainInfo",
            result_path=("DomainInfo",),
            pagination="none",
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeDomainLogs",
            action="DescribeDomainLogs",
            version="2015-01-09",
            resource_type="DomainLogs",
            result_path=("DomainLogs", "DomainLog"),
            page_size=100,
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeDomainNs",
            action="DescribeDomainNs",
            version="2015-01-09",
            resource_type="DomainNs",
            result_path=("DnsServers",),
            pagination="none",
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeDomainDnssecInfo",
            action="DescribeDomainDnssecInfo",
            version="2015-01-09",
            resource_type="DomainDnssecInfo",
            result_path=("DnssecInfo",),
            pagination="none",
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeDomainStatisticsSummary",
            action="DescribeDomainStatisticsSummary",
            version="2015-01-09",
            resource_type="DomainStatisticsSummary",
            result_path=("DomainStatisticsSummary",),
            pagination="none",
            parameters={"StartDate": "__DEFAULT_START_DATE__", "EndDate": "__DEFAULT_END_DATE__"},
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeDomainStatistics",
            action="DescribeDomainStatistics",
            version="2015-01-09",
            resource_type="DomainStatistics",
            result_path=("DomainStatistics",),
            pagination="none",
            parameters={"StartDate": "__DEFAULT_START_DATE__", "EndDate": "__DEFAULT_END_DATE__"},
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeRecordLogs",
            action="DescribeRecordLogs",
            version="2015-01-09",
            resource_type="RecordLogs",
            result_path=("RecordLogs", "RecordLog"),
            page_size=100,
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeRecordStatistics",
            action="DescribeRecordStatistics",
            version="2015-01-09",
            resource_type="RecordStatistics",
            result_path=("RecordStatistics",),
            pagination="none",
            parameters={"StartDate": "__DEFAULT_START_DATE__", "EndDate": "__DEFAULT_END_DATE__"},
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeRecordStatisticsSummary",
            action="DescribeRecordStatisticsSummary",
            version="2015-01-09",
            resource_type="RecordStatisticsSummary",
            result_path=("RecordStatisticsSummary",),
            pagination="none",
            parameters={"StartDate": "__DEFAULT_START_DATE__", "EndDate": "__DEFAULT_END_DATE__"},
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeRecordResolveStatisticsSummary",
            action="DescribeRecordResolveStatisticsSummary",
            version="2015-01-09",
            resource_type="RecordResolveStatisticsSummary",
            result_path=("RecordResolveStatisticsSummary",),
            pagination="none",
            parameters={"StartDate": "__DEFAULT_START_DATE__", "EndDate": "__DEFAULT_END_DATE__"},
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeDomainResolveStatisticsSummary",
            action="DescribeDomainResolveStatisticsSummary",
            version="2015-01-09",
            resource_type="DomainResolveStatisticsSummary",
            result_path=("DomainResolveStatisticsSummary",),
            pagination="none",
            parameters={"StartDate": "__DEFAULT_START_DATE__", "EndDate": "__DEFAULT_END_DATE__"},
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeDomainRecords",
            action="DescribeDomainRecords",
            version="2015-01-09",
            resource_type="DomainRecords",
            result_path=("DomainRecords", "Record"),
            page_size=100,
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeSubDomainRecords",
            action="DescribeSubDomainRecords",
            version="2015-01-09",
            resource_type="SubDomainRecords",
            result_path=("DomainRecords", "Record"),
            page_size=100,
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
    ],
    "kms": [
        AliyunOperation(
            name="ListKeys",
            action="ListKeys",
            version="2016-01-20",
            resource_type="Keys",
            result_path=("Keys", "Key"),
            page_size=100,
        ),
    ],
    "ocr": [],
    "polardb": [
        AliyunOperation(
            name="DescribeDBClusters",
            action="DescribeDBClusters",
            version="2017-08-01",
            resource_type="DBClusters",
            result_path=("Items", "DBCluster"),
            page_size=30,
        ),
    ],
    "privatelink": [
        AliyunOperation(
            name="ListVpcEndpoints",
            action="ListVpcEndpoints",
            version="2020-04-15",
            resource_type="VpcEndpoints",
            result_path=("VpcEndpoints", "VpcEndpoint"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListVpcEndpointServices",
            action="ListVpcEndpointServices",
            version="2020-04-15",
            resource_type="VpcEndpointServices",
            result_path=("VpcEndpointServices", "VpcEndpointService"),
            page_size=50,
        ),
    ],
    "sts": [
        AliyunOperation(
            name="GetCallerIdentity",
            action="GetCallerIdentity",
            version="2015-04-01",
            resource_type="CallerIdentity",
            result_path=("CallerIdentity",),
            pagination="none",
        ),
    ],
    "vpcpeer": [
        AliyunOperation(
            name="DescribeVpcPeerConnections",
            action="DescribeVpcPeerConnections",
            version="2016-04-28",
            resource_type="VpcPeerConnections",
            result_path=("VpcPeerConnections", "VpcPeerConnection"),
            page_size=50,
        ),
    ],
    "dbs": [
        AliyunOperation(
            name="DescribeBackupPlanList",
            action="DescribeBackupPlanList",
            version="2019-03-06",
            resource_type="BackupPlans",
            result_path=("Items", "BackupPlan"),
            page_size=50,
        ),
    ],
    "das": [
        AliyunOperation(
            name="DescribeInstanceList",
            action="DescribeInstanceList",
            version="2020-01-16",
            resource_type="Instances",
            result_path=("Data", "List"),
            page_size=50,
        ),
    ],
    "dds": [
        AliyunOperation(
            name="DescribeDBInstances",
            action="DescribeDBInstances",
            version="2015-12-01",
            resource_type="DBInstances",
            result_path=("DBInstances", "DBInstance"),
            page_size=30,
        ),
    ],
    "alikafka": [
        AliyunOperation(
            name="GetInstanceList",
            action="GetInstanceList",
            version="2019-09-16",
            resource_type="Instances",
            result_path=("InstanceList",),
            page_size=50,
        ),
        AliyunOperation(
            name="GetTopicList",
            action="GetTopicList",
            version="2019-09-16",
            resource_type="Topics",
            result_path=("TopicList",),
            page_size=50,
            iterate_from="GetInstanceList",
            iterate_params={"InstanceId": "InstanceId"},
        ),
        AliyunOperation(
            name="GetConsumerList",
            action="GetConsumerList",
            version="2019-09-16",
            resource_type="Consumers",
            result_path=("ConsumerList",),
            page_size=50,
            iterate_from="GetInstanceList",
            iterate_params={"InstanceId": "InstanceId"},
        ),
    ],
    "mts": [
        AliyunOperation(
            name="QueryPipelineList",
            action="QueryPipelineList",
            version="2014-06-18",
            resource_type="Pipelines",
            result_path=("PipelineList", "Pipeline"),
            pagination="none",
        ),
    ],
    "cloud-siem": [
        AliyunOperation(
            name="DescribeAlerts",
            action="DescribeAlerts",
            version="2022-06-16",
            resource_type="Alerts",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="DescribeAlertsWithEvent",
            action="DescribeAlertsWithEvent",
            version="2022-06-16",
            resource_type="AlertsWithEvent",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="DescribeCloudSiemEvents",
            action="DescribeCloudSiemEvents",
            version="2022-06-16",
            resource_type="Events",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="DescribeCloudSiemAssets",
            action="DescribeCloudSiemAssets",
            version="2022-06-16",
            resource_type="Assets",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListAccountAccessId",
            action="ListAccountAccessId",
            version="2022-06-16",
            resource_type="AccountAccessIds",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListAccountsByLog",
            action="ListAccountsByLog",
            version="2022-06-16",
            resource_type="AccountsByLog",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListAllProds",
            action="ListAllProds",
            version="2022-06-16",
            resource_type="Products",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListAutomateResponseConfigs",
            action="ListAutomateResponseConfigs",
            version="2022-06-16",
            resource_type="AutomateResponseConfigs",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListBindAccount",
            action="ListBindAccount",
            version="2022-06-16",
            resource_type="BindAccounts",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListBindDataSources",
            action="ListBindDataSources",
            version="2022-06-16",
            resource_type="BindDataSources",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListCloudSiemCustomizeRules",
            action="ListCloudSiemCustomizeRules",
            version="2022-06-16",
            resource_type="CustomizeRules",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListCloudSiemPredefinedRules",
            action="ListCloudSiemPredefinedRules",
            version="2022-06-16",
            resource_type="PredefinedRules",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListCustomizeRuleTestResult",
            action="ListCustomizeRuleTestResult",
            version="2022-06-16",
            resource_type="CustomizeRuleTestResults",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListDataSourceLogs",
            action="ListDataSourceLogs",
            version="2022-06-16",
            resource_type="DataSourceLogs",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListDataSourceTypes",
            action="ListDataSourceTypes",
            version="2022-06-16",
            resource_type="DataSourceTypes",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListDelivery",
            action="ListDelivery",
            version="2022-06-16",
            resource_type="Deliveries",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListDisposeStrategy",
            action="ListDisposeStrategy",
            version="2022-06-16",
            resource_type="DisposeStrategies",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListEntities",
            action="ListEntities",
            version="2022-06-16",
            resource_type="Entities",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListImportedLogsByProd",
            action="ListImportedLogsByProd",
            version="2022-06-16",
            resource_type="ImportedLogs",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListProjectLogStores",
            action="ListProjectLogStores",
            version="2022-06-16",
            resource_type="ProjectLogStores",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListRdUsers",
            action="ListRdUsers",
            version="2022-06-16",
            resource_type="RdUsers",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
    ],
    "arms": [
        AliyunOperation(
            name="ListPrometheusInstances",
            action="ListPrometheusInstances",
            version="2019-08-08",
            resource_type="PrometheusInstances",
            result_path=("Data", "Instances"),
            page_size=50,
        ),
    ],
    "adb": [
        AliyunOperation(
            name="DescribeDBClusters",
            action="DescribeDBClusters",
            version="2019-03-15",
            resource_type="DBClusters",
            result_path=("Items", "DBCluster"),
            page_size=30,
        ),
        AliyunOperation(
            name="DescribeDBClusterAttribute",
            action="DescribeDBClusterAttribute",
            version="2019-03-15",
            resource_type="DBClusterAttribute",
            result_path=("Items", "DBCluster"),
            pagination="none",
            iterate_from="DescribeDBClusters",
            iterate_params={"DBClusterId": "DBClusterId"},
        ),
        AliyunOperation(
            name="DescribeDBClusterNetInfo",
            action="DescribeDBClusterNetInfo",
            version="2019-03-15",
            resource_type="DBClusterNetInfo",
            result_path=("Items", "DBClusterNetInfo"),
            pagination="none",
            iterate_from="DescribeDBClusters",
            iterate_params={"DBClusterId": "DBClusterId"},
        ),
        AliyunOperation(
            name="DescribeDBClusterSSL",
            action="DescribeDBClusterSSL",
            version="2019-03-15",
            resource_type="DBClusterSSL",
            result_path=("Items", "DBClusterSSL"),
            pagination="none",
            iterate_from="DescribeDBClusters",
            iterate_params={"DBClusterId": "DBClusterId"},
        ),
        AliyunOperation(
            name="DescribeDBClusterStatus",
            action="DescribeDBClusterStatus",
            version="2019-03-15",
            resource_type="DBClusterStatus",
            result_path=("Items", "DBClusterStatus"),
            pagination="none",
            iterate_from="DescribeDBClusters",
            iterate_params={"DBClusterId": "DBClusterId"},
        ),
        AliyunOperation(
            name="DescribeDBClusterHealthStatus",
            action="DescribeDBClusterHealthStatus",
            version="2019-03-15",
            resource_type="DBClusterHealthStatus",
            result_path=("Items", "DBClusterHealthStatus"),
            pagination="none",
            iterate_from="DescribeDBClusters",
            iterate_params={"DBClusterId": "DBClusterId"},
        ),
        AliyunOperation(
            name="DescribeDBClusterPerformance",
            action="DescribeDBClusterPerformance",
            version="2019-03-15",
            resource_type="DBClusterPerformance",
            result_path=("PerformanceKeys", "PerformanceKey"),
            page_size=30,
            parameters={"StartTime": "__DEFAULT_START_TIME__", "EndTime": "__DEFAULT_END_TIME__"},
            iterate_from="DescribeDBClusters",
            iterate_params={"DBClusterId": "DBClusterId"},
        ),
        AliyunOperation(
            name="DescribeDBClusterSpaceSummary",
            action="DescribeDBClusterSpaceSummary",
            version="2019-03-15",
            resource_type="DBClusterSpaceSummary",
            result_path=("Items", "DBClusterSpaceSummary"),
            pagination="none",
            iterate_from="DescribeDBClusters",
            iterate_params={"DBClusterId": "DBClusterId"},
        ),
        AliyunOperation(
            name="DescribeDBClusterShardNumber",
            action="DescribeDBClusterShardNumber",
            version="2019-03-15",
            resource_type="DBClusterShardNumber",
            result_path=("ShardNumbers", "ShardNumber"),
            pagination="none",
            iterate_from="DescribeDBClusters",
            iterate_params={"DBClusterId": "DBClusterId"},
        ),
        AliyunOperation(
            name="DescribeDBClusterAccessWhiteList",
            action="DescribeDBClusterAccessWhiteList",
            version="2019-03-15",
            resource_type="AccessWhiteList",
            result_path=("Items", "AccessWhiteList"),
            pagination="none",
            iterate_from="DescribeDBClusters",
            iterate_params={"DBClusterId": "DBClusterId"},
        ),
        AliyunOperation(
            name="DescribeBackups",
            action="DescribeBackups",
            version="2019-03-15",
            resource_type="Backups",
            result_path=("Items", "Backup"),
            page_size=30,
            parameters={"StartTime": "__DEFAULT_START_TIME__", "EndTime": "__DEFAULT_END_TIME__"},
            iterate_from="DescribeDBClusters",
            iterate_params={"DBClusterId": "DBClusterId"},
        ),
        AliyunOperation(
            name="DescribeBackupPolicy",
            action="DescribeBackupPolicy",
            version="2019-03-15",
            resource_type="BackupPolicy",
            result_path=("Items", "BackupPolicy"),
            pagination="none",
            iterate_from="DescribeDBClusters",
            iterate_params={"DBClusterId": "DBClusterId"},
        ),
        AliyunOperation(
            name="DescribeAuditLogConfig",
            action="DescribeAuditLogConfig",
            version="2019-03-15",
            resource_type="AuditLogConfig",
            result_path=("Items", "AuditLogConfig"),
            pagination="none",
            iterate_from="DescribeDBClusters",
            iterate_params={"DBClusterId": "DBClusterId"},
        ),
        AliyunOperation(
            name="DescribeAuditLogRecords",
            action="DescribeAuditLogRecords",
            version="2019-03-15",
            resource_type="AuditLogRecords",
            result_path=("Items", "AuditLogRecord"),
            page_size=30,
            parameters={"StartTime": "__DEFAULT_START_TIME__", "EndTime": "__DEFAULT_END_TIME__"},
            iterate_from="DescribeDBClusters",
            iterate_params={"DBClusterId": "DBClusterId"},
        ),
        AliyunOperation(
            name="DescribeSlowLogRecords",
            action="DescribeSlowLogRecords",
            version="2019-03-15",
            resource_type="SlowLogRecords",
            result_path=("Items", "SlowLogRecord"),
            page_size=30,
            parameters={"StartTime": "__DEFAULT_START_TIME__", "EndTime": "__DEFAULT_END_TIME__"},
            iterate_from="DescribeDBClusters",
            iterate_params={"DBClusterId": "DBClusterId"},
        ),
        AliyunOperation(
            name="DescribeProcessList",
            action="DescribeProcessList",
            version="2019-03-15",
            resource_type="ProcessList",
            result_path=("Items", "Process"),
            page_size=50,
            iterate_from="DescribeDBClusters",
            iterate_params={"DBClusterId": "DBClusterId"},
        ),
        AliyunOperation(
            name="DescribeAccounts",
            action="DescribeAccounts",
            version="2019-03-15",
            resource_type="Accounts",
            result_path=("Accounts", "Account"),
            page_size=50,
            iterate_from="DescribeDBClusters",
            iterate_params={"DBClusterId": "DBClusterId"},
        ),
        AliyunOperation(
            name="DescribeAllAccounts",
            action="DescribeAllAccounts",
            version="2019-03-15",
            resource_type="AllAccounts",
            result_path=("Accounts", "Account"),
            page_size=50,
            iterate_from="DescribeDBClusters",
            iterate_params={"DBClusterId": "DBClusterId"},
        ),
        AliyunOperation(
            name="DescribeColumns",
            action="DescribeColumns",
            version="2019-03-15",
            resource_type="Columns",
            result_path=("Columns", "Column"),
            page_size=50,
            iterate_from="DescribeDBClusters",
            iterate_params={"DBClusterId": "DBClusterId"},
        ),
        AliyunOperation(
            name="DescribeTables",
            action="DescribeTables",
            version="2019-03-15",
            resource_type="Tables",
            result_path=("Tables", "Table"),
            page_size=50,
            iterate_from="DescribeDBClusters",
            iterate_params={"DBClusterId": "DBClusterId"},
        ),
        AliyunOperation(
            name="DescribeTableDetail",
            action="DescribeTableDetail",
            version="2019-03-15",
            resource_type="TableDetail",
            result_path=("TableDetail",),
            pagination="none",
            iterate_from="DescribeTables",
            iterate_params={"DBClusterId": "DBClusterId", "TableName": "TableName"},
        ),
        AliyunOperation(
            name="DescribeTableStatistics",
            action="DescribeTableStatistics",
            version="2019-03-15",
            resource_type="TableStatistics",
            result_path=("TableStatistics",),
            pagination="none",
            iterate_from="DescribeTables",
            iterate_params={"DBClusterId": "DBClusterId", "TableName": "TableName"},
        ),
        AliyunOperation(
            name="DescribeTableAccessCount",
            action="DescribeTableAccessCount",
            version="2019-03-15",
            resource_type="TableAccessCount",
            result_path=("TableAccessCount",),
            pagination="none",
            parameters={"StartTime": "__DEFAULT_START_TIME__", "EndTime": "__DEFAULT_END_TIME__"},
            iterate_from="DescribeTables",
            iterate_params={"DBClusterId": "DBClusterId", "TableName": "TableName"},
        ),
        AliyunOperation(
            name="DescribeRegions",
            action="DescribeRegions",
            version="2019-03-15",
            resource_type="Regions",
            result_path=("Regions", "Region"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeVpcs",
            action="DescribeVpcs",
            version="2019-03-15",
            resource_type="Vpcs",
            result_path=("Vpcs", "Vpc"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeVSwitches",
            action="DescribeVSwitches",
            version="2019-03-15",
            resource_type="VSwitches",
            result_path=("VSwitches", "VSwitch"),
            page_size=50,
        ),
    ],
    "cr": [
        AliyunOperation(
            name="ListInstanceRegion",
            action="ListInstanceRegion",
            version="2018-12-01",
            resource_type="InstanceRegions",
            result_path=("Regions",),
            pagination="none",
        ),
        AliyunOperation(
            name="ListInstance",
            action="ListInstance",
            version="2018-12-01",
            resource_type="Instances",
            result_path=("Instances",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListInstanceEndpoint",
            action="ListInstanceEndpoint",
            version="2018-12-01",
            resource_type="InstanceEndpoints",
            result_path=("InstanceEndpoints",),
            page_size=50,
            page_number_param="PageNo",
            iterate_from="ListInstance",
            iterate_params={"InstanceId": "InstanceId"},
        ),
        AliyunOperation(
            name="ListRepository",
            action="ListRepository",
            version="2018-12-01",
            resource_type="Repositories",
            result_path=("Repositories",),
            page_size=50,
            page_number_param="PageNo",
            iterate_from="ListInstance",
            iterate_params={"InstanceId": "InstanceId"},
        ),
        AliyunOperation(
            name="ListRepoSyncRule",
            action="ListRepoSyncRule",
            version="2018-12-01",
            resource_type="RepoSyncRules",
            result_path=("SyncRules",),
            page_size=50,
            page_number_param="PageNo",
            iterate_from="ListInstance",
            iterate_params={"InstanceId": "InstanceId"},
        ),
        AliyunOperation(
            name="ListRepoSyncTask",
            action="ListRepoSyncTask",
            version="2018-12-01",
            resource_type="RepoSyncTasks",
            result_path=("SyncTasks",),
            page_size=50,
            page_number_param="PageNo",
            iterate_from="ListInstance",
            iterate_params={"InstanceId": "InstanceId"},
        ),
        AliyunOperation(
            name="ListRepoTrigger",
            action="ListRepoTrigger",
            version="2018-12-01",
            resource_type="RepoTriggers",
            result_path=("Triggers",),
            page_size=50,
            page_number_param="PageNo",
            iterate_from="ListRepository",
            iterate_params={"InstanceId": "InstanceId", "RepoId": "RepoId"},
        ),
        AliyunOperation(
            name="ListChartNamespace",
            action="ListChartNamespace",
            version="2018-12-01",
            resource_type="ChartNamespaces",
            result_path=("Namespaces",),
            page_size=50,
            page_number_param="PageNo",
            iterate_from="ListInstance",
            iterate_params={"InstanceId": "InstanceId"},
        ),
    ],
    "dms-enterprise": [
        AliyunOperation(
            name="ListAbacAuthorizations",
            action="ListAbacAuthorizations",
            version="2018-11-01",
            resource_type="AbacAuthorizations",
            result_path=("AbacAuthorizations", "AbacAuthorization"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListAbacPolicies",
            action="ListAbacPolicies",
            version="2018-11-01",
            resource_type="AbacPolicies",
            result_path=("AbacPolicies", "AbacPolicy"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListAuthorityTemplate",
            action="ListAuthorityTemplate",
            version="2018-11-01",
            resource_type="AuthorityTemplates",
            result_path=("AuthorityTemplates", "AuthorityTemplate"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListAuthorizedDatabasesForUser",
            action="ListAuthorizedDatabasesForUser",
            version="2018-11-01",
            resource_type="AuthorizedDatabases",
            result_path=("AuthorizedDatabases", "AuthorizedDatabase"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListAuthorizedInstancesForUser",
            action="ListAuthorizedInstancesForUser",
            version="2018-11-01",
            resource_type="AuthorizedInstances",
            result_path=("AuthorizedInstances", "AuthorizedInstance"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListAuthorizedUsersForDatabase",
            action="ListAuthorizedUsersForDatabase",
            version="2018-11-01",
            resource_type="AuthorizedUsersForDatabase",
            result_path=("AuthorizedUsers", "User"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListAuthorizedUsersForInstance",
            action="ListAuthorizedUsersForInstance",
            version="2018-11-01",
            resource_type="AuthorizedUsersForInstance",
            result_path=("AuthorizedUsers", "User"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListClassificationTemplates",
            action="ListClassificationTemplates",
            version="2018-11-01",
            resource_type="ClassificationTemplates",
            result_path=("ClassificationTemplates", "ClassificationTemplate"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListColumns",
            action="ListColumns",
            version="2018-11-01",
            resource_type="Columns",
            result_path=("Columns", "Column"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListDAGVersions",
            action="ListDAGVersions",
            version="2018-11-01",
            resource_type="DAGVersions",
            result_path=("DAGVersions", "DAGVersion"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListDataCorrectPreCheckDB",
            action="ListDataCorrectPreCheckDB",
            version="2018-11-01",
            resource_type="DataCorrectPreCheckDBs",
            result_path=("DBs", "DB"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListDataCorrectPreCheckSQL",
            action="ListDataCorrectPreCheckSQL",
            version="2018-11-01",
            resource_type="DataCorrectPreCheckSQL",
            result_path=("SQLs", "SQL"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListDataImportSQLPreCheckDetail",
            action="ListDataImportSQLPreCheckDetail",
            version="2018-11-01",
            resource_type="DataImportSQLPreCheckDetail",
            result_path=("SQLDetails", "SQLDetail"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListDataImportSQLType",
            action="ListDataImportSQLType",
            version="2018-11-01",
            resource_type="DataImportSQLTypes",
            result_path=("SQLTypes", "SQLType"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListDataLakeCatalog",
            action="ListDataLakeCatalog",
            version="2018-11-01",
            resource_type="DataLakeCatalogs",
            result_path=("Catalogs", "Catalog"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListDataLakeDatabase",
            action="ListDataLakeDatabase",
            version="2018-11-01",
            resource_type="DataLakeDatabases",
            result_path=("Databases", "Database"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListDataLakeFunction",
            action="ListDataLakeFunction",
            version="2018-11-01",
            resource_type="DataLakeFunctions",
            result_path=("Functions", "Function"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListDataLakeFunctionName",
            action="ListDataLakeFunctionName",
            version="2018-11-01",
            resource_type="DataLakeFunctionNames",
            result_path=("FunctionNames", "FunctionName"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListDataLakePartition",
            action="ListDataLakePartition",
            version="2018-11-01",
            resource_type="DataLakePartitions",
            result_path=("Partitions", "Partition"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListDataLakePartitionByFilter",
            action="ListDataLakePartitionByFilter",
            version="2018-11-01",
            resource_type="DataLakePartitions",
            result_path=("Partitions", "Partition"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListDataLakePartitionName",
            action="ListDataLakePartitionName",
            version="2018-11-01",
            resource_type="DataLakePartitionNames",
            result_path=("PartitionNames", "PartitionName"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListDataLakeTable",
            action="ListDataLakeTable",
            version="2018-11-01",
            resource_type="DataLakeTables",
            result_path=("Tables", "Table"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListDataLakeTablebaseInfo",
            action="ListDataLakeTablebaseInfo",
            version="2018-11-01",
            resource_type="DataLakeTableBaseInfo",
            result_path=("TableBaseInfos", "TableBaseInfo"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListDataLakeTableName",
            action="ListDataLakeTableName",
            version="2018-11-01",
            resource_type="DataLakeTableNames",
            result_path=("TableNames", "TableName"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListDatabases",
            action="ListDatabases",
            version="2018-11-01",
            resource_type="Databases",
            result_path=("Databases", "Database"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListDatabaseUserPermssions",
            action="ListDatabaseUserPermssions",
            version="2018-11-01",
            resource_type="DatabaseUserPermissions",
            result_path=("UserPermissions", "UserPermission"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListDDLPublishRecords",
            action="ListDDLPublishRecords",
            version="2018-11-01",
            resource_type="DDLPublishRecords",
            result_path=("Records", "Record"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListDefaultSLARules",
            action="ListDefaultSLARules",
            version="2018-11-01",
            resource_type="DefaultSLARules",
            result_path=("Rules", "Rule"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListDesensitizationRule",
            action="ListDesensitizationRule",
            version="2018-11-01",
            resource_type="DesensitizationRules",
            result_path=("Rules", "Rule"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListEffectiveOrders",
            action="ListEffectiveOrders",
            version="2018-11-01",
            resource_type="EffectiveOrders",
            result_path=("Orders", "Order"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListIndexes",
            action="ListIndexes",
            version="2018-11-01",
            resource_type="Indexes",
            result_path=("Indexes", "Index"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListInstanceLoginAuditLog",
            action="ListInstanceLoginAuditLog",
            version="2018-11-01",
            resource_type="InstanceLoginAuditLogs",
            result_path=("Logs", "Log"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListInstances",
            action="ListInstances",
            version="2018-11-01",
            resource_type="Instances",
            result_path=("Instances", "Instance"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListInstanceUserPermissions",
            action="ListInstanceUserPermissions",
            version="2018-11-01",
            resource_type="InstanceUserPermissions",
            result_path=("UserPermissions", "UserPermission"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListLhTaskFlowAndScenario",
            action="ListLhTaskFlowAndScenario",
            version="2018-11-01",
            resource_type="TaskFlowScenarios",
            result_path=("TaskFlowScenarios", "TaskFlowScenario"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListLogicDatabases",
            action="ListLogicDatabases",
            version="2018-11-01",
            resource_type="LogicDatabases",
            result_path=("LogicDatabases", "LogicDatabase"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListLogicTableRouteConfig",
            action="ListLogicTableRouteConfig",
            version="2018-11-01",
            resource_type="LogicTableRouteConfigs",
            result_path=("TableRouteConfigs", "TableRouteConfig"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListLogicTables",
            action="ListLogicTables",
            version="2018-11-01",
            resource_type="LogicTables",
            result_path=("LogicTables", "LogicTable"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListMetaCategory",
            action="ListMetaCategory",
            version="2018-11-01",
            resource_type="MetaCategories",
            result_path=("MetaCategories", "MetaCategory"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListOrders",
            action="ListOrders",
            version="2018-11-01",
            resource_type="Orders",
            result_path=("Orders", "Order"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListProxies",
            action="ListProxies",
            version="2018-11-01",
            resource_type="Proxies",
            result_path=("Proxies", "Proxy"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListProxyAccesses",
            action="ListProxyAccesses",
            version="2018-11-01",
            resource_type="ProxyAccesses",
            result_path=("ProxyAccesses", "ProxyAccess"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListProxySQLExecAuditLog",
            action="ListProxySQLExecAuditLog",
            version="2018-11-01",
            resource_type="ProxySQLExecAuditLogs",
            result_path=("Logs", "Log"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListScenarios",
            action="ListScenarios",
            version="2018-11-01",
            resource_type="Scenarios",
            result_path=("Scenarios", "Scenario"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListSensitiveColumnInfo",
            action="ListSensitiveColumnInfo",
            version="2018-11-01",
            resource_type="SensitiveColumnInfo",
            result_path=("SensitiveColumnInfoList", "SensitiveColumnInfo"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListSensitiveColumns",
            action="ListSensitiveColumns",
            version="2018-11-01",
            resource_type="SensitiveColumns",
            result_path=("SensitiveColumns", "SensitiveColumn"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListSensitiveColumnsDetail",
            action="ListSensitiveColumnsDetail",
            version="2018-11-01",
            resource_type="SensitiveColumnsDetail",
            result_path=("SensitiveColumnsDetail", "SensitiveColumnDetail"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListSensitiveDataAuditLog",
            action="ListSensitiveDataAuditLog",
            version="2018-11-01",
            resource_type="SensitiveDataAuditLog",
            result_path=("Logs", "Log"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListSensitivityLevel",
            action="ListSensitivityLevel",
            version="2018-11-01",
            resource_type="SensitivityLevels",
            result_path=("SensitivityLevels", "SensitivityLevel"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListSLARules",
            action="ListSLARules",
            version="2018-11-01",
            resource_type="SLARules",
            result_path=("Rules", "Rule"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListSQLExecAuditLog",
            action="ListSQLExecAuditLog",
            version="2018-11-01",
            resource_type="SQLExecAuditLogs",
            result_path=("Logs", "Log"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListSQLReviewOriginSQL",
            action="ListSQLReviewOriginSQL",
            version="2018-11-01",
            resource_type="SQLReviewOriginSQLs",
            result_path=("OriginSQLs", "OriginSQL"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListStandardGroups",
            action="ListStandardGroups",
            version="2018-11-01",
            resource_type="StandardGroups",
            result_path=("StandardGroups", "StandardGroup"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListTableColumns",
            action="ListTableColumns",
            version="2018-11-01",
            resource_type="TableColumns",
            result_path=("TableColumns", "TableColumn"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListTables",
            action="ListTables",
            version="2018-11-01",
            resource_type="Tables",
            result_path=("Tables", "Table"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListTablesInCategory",
            action="ListTablesInCategory",
            version="2018-11-01",
            resource_type="TablesInCategory",
            result_path=("Tables", "Table"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListTaskFlow",
            action="ListTaskFlow",
            version="2018-11-01",
            resource_type="TaskFlows",
            result_path=("TaskFlows", "TaskFlow"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListTaskFlowConstants",
            action="ListTaskFlowConstants",
            version="2018-11-01",
            resource_type="TaskFlowConstants",
            result_path=("TaskFlowConstants", "TaskFlowConstant"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListTaskFlowCooperators",
            action="ListTaskFlowCooperators",
            version="2018-11-01",
            resource_type="TaskFlowCooperators",
            result_path=("Cooperators", "Cooperator"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListTaskFlowEdgesByCondition",
            action="ListTaskFlowEdgesByCondition",
            version="2018-11-01",
            resource_type="TaskFlowEdges",
            result_path=("Edges", "Edge"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListTaskFlowInstance",
            action="ListTaskFlowInstance",
            version="2018-11-01",
            resource_type="TaskFlowInstances",
            result_path=("TaskFlowInstances", "TaskFlowInstance"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListTaskFlowsByPage",
            action="ListTaskFlowsByPage",
            version="2018-11-01",
            resource_type="TaskFlows",
            result_path=("TaskFlows", "TaskFlow"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListTaskFlowTimeVariables",
            action="ListTaskFlowTimeVariables",
            version="2018-11-01",
            resource_type="TaskFlowTimeVariables",
            result_path=("Variables", "Variable"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListTasksInTaskFlow",
            action="ListTasksInTaskFlow",
            version="2018-11-01",
            resource_type="TasksInTaskFlow",
            result_path=("Tasks", "Task"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListUserOwnedResources",
            action="ListUserOwnedResources",
            version="2018-11-01",
            resource_type="UserOwnedResources",
            result_path=("Resources", "Resource"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListUserPermissions",
            action="ListUserPermissions",
            version="2018-11-01",
            resource_type="UserPermissions",
            result_path=("UserPermissions", "UserPermission"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListUsers",
            action="ListUsers",
            version="2018-11-01",
            resource_type="Users",
            result_path=("Users", "User"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListUserTenants",
            action="ListUserTenants",
            version="2018-11-01",
            resource_type="UserTenants",
            result_path=("UserTenants", "UserTenant"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListWorkFlowNodes",
            action="ListWorkFlowNodes",
            version="2018-11-01",
            resource_type="WorkFlowNodes",
            result_path=("Nodes", "Node"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListWorkFlowTemplates",
            action="ListWorkFlowTemplates",
            version="2018-11-01",
            resource_type="WorkFlowTemplates",
            result_path=("Templates", "Template"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListWorkspaces",
            action="ListWorkspaces",
            version="2018-11-01",
            resource_type="Workspaces",
            result_path=("Workspaces", "Workspace"),
            page_size=50,
        ),
    ],
    "actiontrail": [
        AliyunOperation(
            name="DescribeTrails",
            action="DescribeTrails",
            version="2020-07-06",
            resource_type="Trails",
            result_path=("TrailList",),
            pagination="none",
        ),
    ],
    "ebs": [
        AliyunOperation(
            name="DescribeDedicatedBlockStorageClusters",
            action="DescribeDedicatedBlockStorageClusters",
            version="2021-07-30",
            resource_type="DedicatedBlockStorageClusters",
            result_path=("DedicatedBlockStorageClusters", "Dbsc"),
            pagination="token",
            page_size=50,
        ),
    ],
    "eci": [
        AliyunOperation(
            name="DescribeContainerGroups",
            action="DescribeContainerGroups",
            version="2018-08-08",
            resource_type="ContainerGroups",
            result_path=("ContainerGroups",),
            pagination="token",
            page_size=20,
            limit_param="Limit",
        ),
    ],
    "ros": [
        AliyunOperation(
            name="ListStacks",
            action="ListStacks",
            version="2019-09-10",
            resource_type="Stacks",
            result_path=("Stacks", "Stack"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListStackEvents",
            action="ListStackEvents",
            version="2019-09-10",
            resource_type="StackEvents",
            result_path=("Events", "Event"),
            page_size=50,
            iterate_from="ListStacks",
            iterate_params={"StackId": "StackId"},
        ),
        AliyunOperation(
            name="ListStackResources",
            action="ListStackResources",
            version="2019-09-10",
            resource_type="StackResources",
            result_path=("Resources", "Resource"),
            page_size=50,
            iterate_from="ListStacks",
            iterate_params={"StackId": "StackId"},
        ),
        AliyunOperation(
            name="ListStackResourceDrifts",
            action="ListStackResourceDrifts",
            version="2019-09-10",
            resource_type="StackResourceDrifts",
            result_path=("ResourceDrifts", "ResourceDrift"),
            page_size=50,
            iterate_from="ListStacks",
            iterate_params={"StackId": "StackId"},
        ),
        AliyunOperation(
            name="ListChangeSets",
            action="ListChangeSets",
            version="2019-09-10",
            resource_type="ChangeSets",
            result_path=("ChangeSets", "ChangeSet"),
            page_size=50,
            iterate_from="ListStacks",
            iterate_params={"StackId": "StackId"},
        ),
        AliyunOperation(
            name="ListStackGroups",
            action="ListStackGroups",
            version="2019-09-10",
            resource_type="StackGroups",
            result_path=("StackGroups", "StackGroup"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListStackInstances",
            action="ListStackInstances",
            version="2019-09-10",
            resource_type="StackInstances",
            result_path=("StackInstances", "StackInstance"),
            page_size=50,
            iterate_from="ListStackGroups",
            iterate_params={"StackGroupName": "StackGroupName"},
        ),
        AliyunOperation(
            name="ListStackGroupOperations",
            action="ListStackGroupOperations",
            version="2019-09-10",
            resource_type="StackGroupOperations",
            result_path=("StackGroupOperations", "StackGroupOperation"),
            page_size=50,
            iterate_from="ListStackGroups",
            iterate_params={"StackGroupName": "StackGroupName"},
        ),
        AliyunOperation(
            name="ListStackGroupOperationResults",
            action="ListStackGroupOperationResults",
            version="2019-09-10",
            resource_type="StackGroupOperationResults",
            result_path=("StackGroupOperationResults", "StackGroupOperationResult"),
            page_size=50,
            iterate_from="ListStackGroupOperations",
            iterate_params={"StackGroupName": "StackGroupName", "OperationId": "OperationId"},
        ),
        AliyunOperation(
            name="ListTemplates",
            action="ListTemplates",
            version="2019-09-10",
            resource_type="Templates",
            result_path=("Templates", "Template"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListResourceTypes",
            action="ListResourceTypes",
            version="2019-09-10",
            resource_type="ResourceTypes",
            result_path=("ResourceTypes", "ResourceType"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListResourceTypeVersions",
            action="ListResourceTypeVersions",
            version="2019-09-10",
            resource_type="ResourceTypeVersions",
            result_path=("ResourceTypeVersions", "ResourceTypeVersion"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListResourceTypeRegistrations",
            action="ListResourceTypeRegistrations",
            version="2019-09-10",
            resource_type="ResourceTypeRegistrations",
            result_path=("ResourceTypeRegistrations", "ResourceTypeRegistration"),
            page_size=50,
        ),
    ],
}


def get_services():
    return sorted(ALIYUN_OPERATIONS.keys())


def get_operations(service):
    return ALIYUN_OPERATIONS.get(service, [])


def get_service_spec(service):
    return SERVICE_SPECS.get(service)
