from dataclasses import dataclass


@dataclass(frozen=True)
class AliyunOperation:
    name: str
    action: str
    version: str
    resource_type: str
    result_path: tuple
    method: str = "POST"
    parameters: dict = None
    pagination: str = "page"  # page, marker, token, none
    page_size: int = 50
    token_param: str = "NextToken"
    limit_param: str = "MaxResults"
    page_number_param: str = "PageNumber"
    page_size_param: str = "PageSize"
    iterate_from: str = None
    iterate_param: str = None
    iterate_field: str = None
    iterate_params: dict = None


@dataclass(frozen=True)
class AliyunServiceSpec:
    endpoint_template: str
    regional: bool = True


SERVICE_SPECS = {
    "ecs": AliyunServiceSpec(endpoint_template="ecs.{region}.aliyuncs.com"),
    "vpc": AliyunServiceSpec(endpoint_template="vpc.{region}.aliyuncs.com"),
    "slb": AliyunServiceSpec(endpoint_template="slb.{region}.aliyuncs.com"),
    "rds": AliyunServiceSpec(endpoint_template="rds.{region}.aliyuncs.com"),
    "ram": AliyunServiceSpec(endpoint_template="ram.aliyuncs.com", regional=False),
    "nas": AliyunServiceSpec(endpoint_template="nas.{region}.aliyuncs.com"),
    "oss": AliyunServiceSpec(endpoint_template="oss-{region}.aliyuncs.com"),
    "alb": AliyunServiceSpec(endpoint_template="alb.{region}.aliyuncs.com"),
    "cdn": AliyunServiceSpec(endpoint_template="cdn.aliyuncs.com", regional=False),
    "actiontrail": AliyunServiceSpec(endpoint_template="actiontrail.{region}.aliyuncs.com"),
    "ebs": AliyunServiceSpec(endpoint_template="ebs.{region}.aliyuncs.com"),
    "eci": AliyunServiceSpec(endpoint_template="eci.{region}.aliyuncs.com"),
    "ros": AliyunServiceSpec(endpoint_template="ros.aliyuncs.com", regional=False),
    "drds": AliyunServiceSpec(endpoint_template="drds.{region}.aliyuncs.com"),
    "domain": AliyunServiceSpec(endpoint_template="domain.aliyuncs.com", regional=False),
    "elasticsearch": AliyunServiceSpec(endpoint_template="elasticsearch.{region}.aliyuncs.com"),
    "alidns": AliyunServiceSpec(endpoint_template="alidns.aliyuncs.com", regional=False),
    "kms": AliyunServiceSpec(endpoint_template="kms.{region}.aliyuncs.com"),
    "ocr": AliyunServiceSpec(endpoint_template="ocr.{region}.aliyuncs.com"),
    "polardb": AliyunServiceSpec(endpoint_template="polardb.{region}.aliyuncs.com"),
    "privatelink": AliyunServiceSpec(endpoint_template="privatelink.{region}.aliyuncs.com"),
    "sts": AliyunServiceSpec(endpoint_template="sts.aliyuncs.com", regional=False),
    "vpcpeer": AliyunServiceSpec(endpoint_template="vpc.{region}.aliyuncs.com"),
    "dbs": AliyunServiceSpec(endpoint_template="dbs.{region}.aliyuncs.com"),
    "das": AliyunServiceSpec(endpoint_template="das.{region}.aliyuncs.com"),
    "dds": AliyunServiceSpec(endpoint_template="dds.{region}.aliyuncs.com"),
    "alikafka": AliyunServiceSpec(endpoint_template="alikafka.{region}.aliyuncs.com"),
    "mts": AliyunServiceSpec(endpoint_template="mts.{region}.aliyuncs.com"),
    "cloud-siem": AliyunServiceSpec(endpoint_template="cloud-siem.{region}.aliyuncs.com"),
    "arms": AliyunServiceSpec(endpoint_template="arms.{region}.aliyuncs.com"),
}


ALIYUN_OPERATIONS = {
    "ecs": [
        AliyunOperation(
            name="DescribeInstances",
            action="DescribeInstances",
            version="2014-05-26",
            resource_type="Instances",
            result_path=("Instances", "Instance"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeDisks",
            action="DescribeDisks",
            version="2014-05-26",
            resource_type="Disks",
            result_path=("Disks", "Disk"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeSecurityGroups",
            action="DescribeSecurityGroups",
            version="2014-05-26",
            resource_type="SecurityGroups",
            result_path=("SecurityGroups", "SecurityGroup"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeSnapshots",
            action="DescribeSnapshots",
            version="2014-05-26",
            resource_type="Snapshots",
            result_path=("Snapshots", "Snapshot"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeImages",
            action="DescribeImages",
            version="2014-05-26",
            resource_type="Images",
            result_path=("Images", "Image"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeInstanceAttribute",
            action="DescribeInstanceAttribute",
            version="2014-05-26",
            resource_type="InstanceAttribute",
            result_path=("Instance",),
            pagination="none",
            iterate_from="DescribeInstances",
            iterate_params={"InstanceId": "InstanceId"},
        ),
        AliyunOperation(
            name="DescribeSecurityGroupAttribute",
            action="DescribeSecurityGroupAttribute",
            version="2014-05-26",
            resource_type="SecurityGroupAttribute",
            result_path=("Permissions", "Permission"),
            pagination="none",
            iterate_from="DescribeSecurityGroups",
            iterate_params={"SecurityGroupId": "SecurityGroupId"},
        ),
        AliyunOperation(
            name="DescribeDiskAttribute",
            action="DescribeDiskAttribute",
            version="2014-05-26",
            resource_type="DiskAttribute",
            result_path=("Disk",),
            pagination="none",
            iterate_from="DescribeDisks",
            iterate_params={"DiskId": "DiskId"},
        ),
        AliyunOperation(
            name="DescribeSnapshotAttribute",
            action="DescribeSnapshotAttribute",
            version="2014-05-26",
            resource_type="SnapshotAttribute",
            result_path=("Snapshot",),
            pagination="none",
            iterate_from="DescribeSnapshots",
            iterate_params={"SnapshotId": "SnapshotId"},
        ),
    ],
    "vpc": [
        AliyunOperation(
            name="DescribeVpcs",
            action="DescribeVpcs",
            version="2016-04-28",
            resource_type="Vpcs",
            result_path=("Vpcs", "Vpc"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeVSwitches",
            action="DescribeVSwitches",
            version="2016-04-28",
            resource_type="VSwitches",
            result_path=("VSwitches", "VSwitch"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeEipAddresses",
            action="DescribeEipAddresses",
            version="2016-04-28",
            resource_type="EipAddresses",
            result_path=("EipAddresses", "EipAddress"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeNatGateways",
            action="DescribeNatGateways",
            version="2016-04-28",
            resource_type="NatGateways",
            result_path=("NatGateways", "NatGateway"),
            page_size=50,
        ),
    ],
    "slb": [
        AliyunOperation(
            name="DescribeLoadBalancers",
            action="DescribeLoadBalancers",
            version="2014-05-15",
            resource_type="LoadBalancers",
            result_path=("LoadBalancers", "LoadBalancer"),
            page_size=50,
        ),
    ],
    "rds": [
        AliyunOperation(
            name="DescribeDBInstances",
            action="DescribeDBInstances",
            version="2014-08-15",
            resource_type="DBInstances",
            result_path=("Items", "DBInstance"),
            page_size=30,
        ),
        AliyunOperation(
            name="DescribeDBInstanceAttribute",
            action="DescribeDBInstanceAttribute",
            version="2014-08-15",
            resource_type="DBInstanceAttributes",
            result_path=("Items", "DBInstanceAttribute"),
            pagination="none",
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
        AliyunOperation(
            name="DescribeAccounts",
            action="DescribeAccounts",
            version="2014-08-15",
            resource_type="DBAccounts",
            result_path=("Accounts", "DBInstanceAccount"),
            pagination="none",
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
        AliyunOperation(
            name="DescribeDatabaseNames",
            action="DescribeDatabaseNames",
            version="2014-08-15",
            resource_type="Databases",
            result_path=("Databases", "Database"),
            pagination="none",
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
        AliyunOperation(
            name="DescribeDBInstanceIPs",
            action="DescribeDBInstanceIPs",
            version="2014-08-15",
            resource_type="DBInstanceIPs",
            result_path=("Items", "DBInstanceIP"),
            pagination="none",
            iterate_from="DescribeDBInstances",
            iterate_params={"DBInstanceId": "DBInstanceId"},
        ),
    ],
    "alb": [
        AliyunOperation(
            name="ListLoadBalancers",
            action="ListLoadBalancers",
            version="2020-06-16",
            resource_type="LoadBalancers",
            result_path=("LoadBalancers",),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
        ),
        AliyunOperation(
            name="ListListeners",
            action="ListListeners",
            version="2020-06-16",
            resource_type="Listeners",
            result_path=("Listeners",),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
            iterate_from="ListLoadBalancers",
            iterate_params={"LoadBalancerIds.1": "LoadBalancerId"},
        ),
        AliyunOperation(
            name="ListRules",
            action="ListRules",
            version="2020-06-16",
            resource_type="Rules",
            result_path=("Rules",),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
            iterate_from="ListListeners",
            iterate_params={"ListenerIds.1": "ListenerId"},
        ),
        AliyunOperation(
            name="ListServerGroups",
            action="ListServerGroups",
            version="2020-06-16",
            resource_type="ServerGroups",
            result_path=("ServerGroups",),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
            iterate_from="ListLoadBalancers",
            iterate_params={"LoadBalancerIds.1": "LoadBalancerId"},
        ),
        AliyunOperation(
            name="ListServerGroupServers",
            action="ListServerGroupServers",
            version="2020-06-16",
            resource_type="ServerGroupServers",
            result_path=("Servers", "Server"),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
            iterate_from="ListServerGroups",
            iterate_params={"ServerGroupId": "ServerGroupId"},
        ),
        AliyunOperation(
            name="ListSecurityPolicies",
            action="ListSecurityPolicies",
            version="2020-06-16",
            resource_type="SecurityPolicies",
            result_path=("SecurityPolicies",),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
        ),
        AliyunOperation(
            name="ListSecurityPolicyRelations",
            action="ListSecurityPolicyRelations",
            version="2020-06-16",
            resource_type="SecurityPolicyRelations",
            result_path=("SecurityPolicyRelations",),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
            iterate_from="ListSecurityPolicies",
            iterate_params={"SecurityPolicyIds.1": "SecurityPolicyId"},
        ),
        AliyunOperation(
            name="ListSystemSecurityPolicies",
            action="ListSystemSecurityPolicies",
            version="2020-06-16",
            resource_type="SystemSecurityPolicies",
            result_path=("SystemSecurityPolicies",),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
        ),
        AliyunOperation(
            name="ListListenerCertificates",
            action="ListListenerCertificates",
            version="2020-06-16",
            resource_type="ListenerCertificates",
            result_path=("Certificates", "Certificate"),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
            iterate_from="ListListeners",
            iterate_params={"ListenerId": "ListenerId"},
        ),
        AliyunOperation(
            name="ListTagKeys",
            action="ListTagKeys",
            version="2020-06-16",
            resource_type="TagKeys",
            result_path=("TagKeys",),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
        ),
        AliyunOperation(
            name="ListTagValues",
            action="ListTagValues",
            version="2020-06-16",
            resource_type="TagValues",
            result_path=("TagValues",),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
        ),
        AliyunOperation(
            name="ListTagResources",
            action="ListTagResources",
            version="2020-06-16",
            resource_type="TagResources",
            result_path=("TagResources", "TagResource"),
            page_size=50,
            pagination="token",
            limit_param="MaxResults",
            token_param="NextToken",
            iterate_from="ListLoadBalancers",
            iterate_params={"ResourceId.1": "LoadBalancerId", "ResourceType": "LoadBalancer"},
        ),
    ],
    "cdn": [
        AliyunOperation(
            name="DescribeUserDomains",
            action="DescribeUserDomains",
            version="2018-05-10",
            resource_type="Domains",
            result_path=("Domains", "PageData"),
            page_size=50,
        ),
    ],
    "ram": [
        AliyunOperation(
            name="ListUsers",
            action="ListUsers",
            version="2015-05-01",
            resource_type="Users",
            result_path=("Users", "User"),
            pagination="marker",
            page_size=100,
        ),
        AliyunOperation(
            name="ListAccessKeys",
            action="ListAccessKeys",
            version="2015-05-01",
            resource_type="AccessKeys",
            result_path=("AccessKeys", "AccessKey"),
            pagination="marker",
            page_size=100,
            iterate_from="ListUsers",
            iterate_params={"UserName": "UserName"},
        ),
        AliyunOperation(
            name="ListRoles",
            action="ListRoles",
            version="2015-05-01",
            resource_type="Roles",
            result_path=("Roles", "Role"),
            pagination="marker",
            page_size=100,
        ),
        AliyunOperation(
            name="ListPolicies",
            action="ListPolicies",
            version="2015-05-01",
            resource_type="Policies",
            result_path=("Policies", "Policy"),
            pagination="marker",
            page_size=100,
        ),
        AliyunOperation(
            name="ListPolicyVersions",
            action="ListPolicyVersions",
            version="2015-05-01",
            resource_type="PolicyVersions",
            result_path=("PolicyVersions", "PolicyVersion"),
            pagination="marker",
            page_size=100,
            iterate_from="ListPolicies",
            iterate_params={"PolicyName": "PolicyName", "PolicyType": "PolicyType"},
        ),
        AliyunOperation(
            name="ListGroups",
            action="ListGroups",
            version="2015-05-01",
            resource_type="Groups",
            result_path=("Groups", "Group"),
            pagination="marker",
            page_size=100,
        ),
        AliyunOperation(
            name="ListEntitiesForPolicy",
            action="ListEntitiesForPolicy",
            version="2015-05-01",
            resource_type="EntitiesForPolicy",
            result_path=("PolicyGroups",),
            pagination="marker",
            page_size=100,
            iterate_from="ListPolicies",
            iterate_params={"PolicyName": "PolicyName", "PolicyType": "PolicyType"},
        ),
        AliyunOperation(
            name="ListGroupsForUser",
            action="ListGroupsForUser",
            version="2015-05-01",
            resource_type="GroupsForUser",
            result_path=("Groups", "Group"),
            pagination="marker",
            page_size=100,
            iterate_from="ListUsers",
            iterate_params={"UserName": "UserName"},
        ),
        AliyunOperation(
            name="ListPoliciesForGroup",
            action="ListPoliciesForGroup",
            version="2015-05-01",
            resource_type="PoliciesForGroup",
            result_path=("Policies", "Policy"),
            pagination="marker",
            page_size=100,
            iterate_from="ListGroups",
            iterate_params={"GroupName": "GroupName"},
        ),
        AliyunOperation(
            name="ListPoliciesForRole",
            action="ListPoliciesForRole",
            version="2015-05-01",
            resource_type="PoliciesForRole",
            result_path=("Policies", "Policy"),
            pagination="marker",
            page_size=100,
            iterate_from="ListRoles",
            iterate_params={"RoleName": "RoleName"},
        ),
        AliyunOperation(
            name="ListPoliciesForUser",
            action="ListPoliciesForUser",
            version="2015-05-01",
            resource_type="PoliciesForUser",
            result_path=("Policies", "Policy"),
            pagination="marker",
            page_size=100,
            iterate_from="ListUsers",
            iterate_params={"UserName": "UserName"},
        ),
        AliyunOperation(
            name="ListUsersForGroup",
            action="ListUsersForGroup",
            version="2015-05-01",
            resource_type="UsersForGroup",
            result_path=("Users", "User"),
            pagination="marker",
            page_size=100,
            iterate_from="ListGroups",
            iterate_params={"GroupName": "GroupName"},
        ),
        AliyunOperation(
            name="ListVirtualMFADevices",
            action="ListVirtualMFADevices",
            version="2015-05-01",
            resource_type="VirtualMFADevices",
            result_path=("VirtualMFADevices", "VirtualMFADevice"),
            pagination="marker",
            page_size=100,
        ),
    ],
    "nas": [
        AliyunOperation(
            name="DescribeFileSystems",
            action="DescribeFileSystems",
            version="2017-06-26",
            resource_type="FileSystems",
            result_path=("FileSystems", "FileSystem"),
            page_size=50,
        ),
        AliyunOperation(
            name="DescribeMountTargets",
            action="DescribeMountTargets",
            version="2017-06-26",
            resource_type="MountTargets",
            result_path=("MountTargets", "MountTarget"),
            page_size=50,
        ),
    ],
    "oss": [
        AliyunOperation(
            name="ListBuckets",
            action="ListBuckets",
            version="2013-10-15",
            resource_type="Buckets",
            result_path=("Buckets",),
            pagination="none",
        ),
    ],
    "drds": [
        AliyunOperation(
            name="DescribeDrdsInstances",
            action="DescribeDrdsInstances",
            version="2019-01-23",
            resource_type="DrdsInstances",
            result_path=("DrdsInstances", "DrdsInstance"),
            page_size=50,
        ),
    ],
    "domain": [
        AliyunOperation(
            name="QueryDomainList",
            action="QueryDomainList",
            version="2018-01-29",
            resource_type="Domains",
            result_path=("Data", "Domain"),
            page_size=50,
            page_number_param="PageNum",
        ),
    ],
    "elasticsearch": [
        AliyunOperation(
            name="ListInstance",
            action="ListInstance",
            version="2017-06-13",
            resource_type="Instances",
            result_path=("Result", "Instance"),
            page_size=20,
        ),
    ],
    "alidns": [
        AliyunOperation(
            name="DescribeDomains",
            action="DescribeDomains",
            version="2015-01-09",
            resource_type="Domains",
            result_path=("Domains", "Domain"),
            page_size=100,
        ),
        AliyunOperation(
            name="DescribeDomainGroups",
            action="DescribeDomainGroups",
            version="2015-01-09",
            resource_type="DomainGroups",
            result_path=("DomainGroups", "DomainGroup"),
            page_size=100,
        ),
        AliyunOperation(
            name="DescribeSupportLines",
            action="DescribeSupportLines",
            version="2015-01-09",
            resource_type="SupportLines",
            result_path=("RecordLines", "RecordLine"),
            pagination="none",
        ),
        AliyunOperation(
            name="DescribeCustomLines",
            action="DescribeCustomLines",
            version="2015-01-09",
            resource_type="CustomLines",
            result_path=("CustomLines", "CustomLine"),
            page_size=100,
        ),
        AliyunOperation(
            name="DescribeDnsCacheDomains",
            action="DescribeDnsCacheDomains",
            version="2015-01-09",
            resource_type="DnsCacheDomains",
            result_path=("Domains", "Domain"),
            page_size=100,
        ),
        AliyunOperation(
            name="DescribeTags",
            action="DescribeTags",
            version="2015-01-09",
            resource_type="Tags",
            result_path=("Tags", "Tag"),
            page_size=100,
        ),
        AliyunOperation(
            name="DescribeDomainInfo",
            action="DescribeDomainInfo",
            version="2015-01-09",
            resource_type="DomainInfo",
            result_path=("DomainInfo",),
            pagination="none",
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeDomainLogs",
            action="DescribeDomainLogs",
            version="2015-01-09",
            resource_type="DomainLogs",
            result_path=("DomainLogs", "DomainLog"),
            page_size=100,
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeDomainNs",
            action="DescribeDomainNs",
            version="2015-01-09",
            resource_type="DomainNs",
            result_path=("DnsServers",),
            pagination="none",
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeDomainDnssecInfo",
            action="DescribeDomainDnssecInfo",
            version="2015-01-09",
            resource_type="DomainDnssecInfo",
            result_path=("DnssecInfo",),
            pagination="none",
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeDomainStatisticsSummary",
            action="DescribeDomainStatisticsSummary",
            version="2015-01-09",
            resource_type="DomainStatisticsSummary",
            result_path=("DomainStatisticsSummary",),
            pagination="none",
            parameters={"StartDate": "__DEFAULT_START_DATE__", "EndDate": "__DEFAULT_END_DATE__"},
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeDomainStatistics",
            action="DescribeDomainStatistics",
            version="2015-01-09",
            resource_type="DomainStatistics",
            result_path=("DomainStatistics",),
            pagination="none",
            parameters={"StartDate": "__DEFAULT_START_DATE__", "EndDate": "__DEFAULT_END_DATE__"},
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeRecordLogs",
            action="DescribeRecordLogs",
            version="2015-01-09",
            resource_type="RecordLogs",
            result_path=("RecordLogs", "RecordLog"),
            page_size=100,
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeRecordStatistics",
            action="DescribeRecordStatistics",
            version="2015-01-09",
            resource_type="RecordStatistics",
            result_path=("RecordStatistics",),
            pagination="none",
            parameters={"StartDate": "__DEFAULT_START_DATE__", "EndDate": "__DEFAULT_END_DATE__"},
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeRecordStatisticsSummary",
            action="DescribeRecordStatisticsSummary",
            version="2015-01-09",
            resource_type="RecordStatisticsSummary",
            result_path=("RecordStatisticsSummary",),
            pagination="none",
            parameters={"StartDate": "__DEFAULT_START_DATE__", "EndDate": "__DEFAULT_END_DATE__"},
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeRecordResolveStatisticsSummary",
            action="DescribeRecordResolveStatisticsSummary",
            version="2015-01-09",
            resource_type="RecordResolveStatisticsSummary",
            result_path=("RecordResolveStatisticsSummary",),
            pagination="none",
            parameters={"StartDate": "__DEFAULT_START_DATE__", "EndDate": "__DEFAULT_END_DATE__"},
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeDomainResolveStatisticsSummary",
            action="DescribeDomainResolveStatisticsSummary",
            version="2015-01-09",
            resource_type="DomainResolveStatisticsSummary",
            result_path=("DomainResolveStatisticsSummary",),
            pagination="none",
            parameters={"StartDate": "__DEFAULT_START_DATE__", "EndDate": "__DEFAULT_END_DATE__"},
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeDomainRecords",
            action="DescribeDomainRecords",
            version="2015-01-09",
            resource_type="DomainRecords",
            result_path=("DomainRecords", "Record"),
            page_size=100,
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
        AliyunOperation(
            name="DescribeSubDomainRecords",
            action="DescribeSubDomainRecords",
            version="2015-01-09",
            resource_type="SubDomainRecords",
            result_path=("DomainRecords", "Record"),
            page_size=100,
            iterate_from="DescribeDomains",
            iterate_param="DomainName",
            iterate_field="DomainName",
        ),
    ],
    "kms": [
        AliyunOperation(
            name="ListKeys",
            action="ListKeys",
            version="2016-01-20",
            resource_type="Keys",
            result_path=("Keys", "Key"),
            page_size=100,
        ),
    ],
    "ocr": [],
    "polardb": [
        AliyunOperation(
            name="DescribeDBClusters",
            action="DescribeDBClusters",
            version="2017-08-01",
            resource_type="DBClusters",
            result_path=("Items", "DBCluster"),
            page_size=30,
        ),
    ],
    "privatelink": [
        AliyunOperation(
            name="ListVpcEndpoints",
            action="ListVpcEndpoints",
            version="2020-04-15",
            resource_type="VpcEndpoints",
            result_path=("VpcEndpoints", "VpcEndpoint"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListVpcEndpointServices",
            action="ListVpcEndpointServices",
            version="2020-04-15",
            resource_type="VpcEndpointServices",
            result_path=("VpcEndpointServices", "VpcEndpointService"),
            page_size=50,
        ),
    ],
    "sts": [
        AliyunOperation(
            name="GetCallerIdentity",
            action="GetCallerIdentity",
            version="2015-04-01",
            resource_type="CallerIdentity",
            result_path=("CallerIdentity",),
            pagination="none",
        ),
    ],
    "vpcpeer": [
        AliyunOperation(
            name="DescribeVpcPeerConnections",
            action="DescribeVpcPeerConnections",
            version="2016-04-28",
            resource_type="VpcPeerConnections",
            result_path=("VpcPeerConnections", "VpcPeerConnection"),
            page_size=50,
        ),
    ],
    "dbs": [
        AliyunOperation(
            name="DescribeBackupPlanList",
            action="DescribeBackupPlanList",
            version="2019-03-06",
            resource_type="BackupPlans",
            result_path=("Items", "BackupPlan"),
            page_size=50,
        ),
    ],
    "das": [
        AliyunOperation(
            name="DescribeInstanceList",
            action="DescribeInstanceList",
            version="2020-01-16",
            resource_type="Instances",
            result_path=("Data", "List"),
            page_size=50,
        ),
    ],
    "dds": [
        AliyunOperation(
            name="DescribeDBInstances",
            action="DescribeDBInstances",
            version="2015-12-01",
            resource_type="DBInstances",
            result_path=("DBInstances", "DBInstance"),
            page_size=30,
        ),
    ],
    "alikafka": [
        AliyunOperation(
            name="GetInstanceList",
            action="GetInstanceList",
            version="2019-09-16",
            resource_type="Instances",
            result_path=("InstanceList",),
            page_size=50,
        ),
        AliyunOperation(
            name="GetTopicList",
            action="GetTopicList",
            version="2019-09-16",
            resource_type="Topics",
            result_path=("TopicList",),
            page_size=50,
            iterate_from="GetInstanceList",
            iterate_params={"InstanceId": "InstanceId"},
        ),
        AliyunOperation(
            name="GetConsumerList",
            action="GetConsumerList",
            version="2019-09-16",
            resource_type="Consumers",
            result_path=("ConsumerList",),
            page_size=50,
            iterate_from="GetInstanceList",
            iterate_params={"InstanceId": "InstanceId"},
        ),
    ],
    "mts": [
        AliyunOperation(
            name="QueryPipelineList",
            action="QueryPipelineList",
            version="2014-06-18",
            resource_type="Pipelines",
            result_path=("PipelineList", "Pipeline"),
            pagination="none",
        ),
    ],
    "cloud-siem": [
        AliyunOperation(
            name="DescribeAlerts",
            action="DescribeAlerts",
            version="2022-06-16",
            resource_type="Alerts",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="DescribeAlertsWithEvent",
            action="DescribeAlertsWithEvent",
            version="2022-06-16",
            resource_type="AlertsWithEvent",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="DescribeCloudSiemEvents",
            action="DescribeCloudSiemEvents",
            version="2022-06-16",
            resource_type="Events",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="DescribeCloudSiemAssets",
            action="DescribeCloudSiemAssets",
            version="2022-06-16",
            resource_type="Assets",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListAccountAccessId",
            action="ListAccountAccessId",
            version="2022-06-16",
            resource_type="AccountAccessIds",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListAccountsByLog",
            action="ListAccountsByLog",
            version="2022-06-16",
            resource_type="AccountsByLog",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListAllProds",
            action="ListAllProds",
            version="2022-06-16",
            resource_type="Products",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListAutomateResponseConfigs",
            action="ListAutomateResponseConfigs",
            version="2022-06-16",
            resource_type="AutomateResponseConfigs",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListBindAccount",
            action="ListBindAccount",
            version="2022-06-16",
            resource_type="BindAccounts",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListBindDataSources",
            action="ListBindDataSources",
            version="2022-06-16",
            resource_type="BindDataSources",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListCloudSiemCustomizeRules",
            action="ListCloudSiemCustomizeRules",
            version="2022-06-16",
            resource_type="CustomizeRules",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListCloudSiemPredefinedRules",
            action="ListCloudSiemPredefinedRules",
            version="2022-06-16",
            resource_type="PredefinedRules",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListCustomizeRuleTestResult",
            action="ListCustomizeRuleTestResult",
            version="2022-06-16",
            resource_type="CustomizeRuleTestResults",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListDataSourceLogs",
            action="ListDataSourceLogs",
            version="2022-06-16",
            resource_type="DataSourceLogs",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListDataSourceTypes",
            action="ListDataSourceTypes",
            version="2022-06-16",
            resource_type="DataSourceTypes",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListDelivery",
            action="ListDelivery",
            version="2022-06-16",
            resource_type="Deliveries",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListDisposeStrategy",
            action="ListDisposeStrategy",
            version="2022-06-16",
            resource_type="DisposeStrategies",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListEntities",
            action="ListEntities",
            version="2022-06-16",
            resource_type="Entities",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListImportedLogsByProd",
            action="ListImportedLogsByProd",
            version="2022-06-16",
            resource_type="ImportedLogs",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListProjectLogStores",
            action="ListProjectLogStores",
            version="2022-06-16",
            resource_type="ProjectLogStores",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
        AliyunOperation(
            name="ListRdUsers",
            action="ListRdUsers",
            version="2022-06-16",
            resource_type="RdUsers",
            result_path=("Data",),
            page_size=50,
            page_number_param="PageNo",
        ),
    ],
    "arms": [
        AliyunOperation(
            name="ListPrometheusInstances",
            action="ListPrometheusInstances",
            version="2019-08-08",
            resource_type="PrometheusInstances",
            result_path=("Data", "Instances"),
            page_size=50,
        ),
    ],
    "actiontrail": [
        AliyunOperation(
            name="DescribeTrails",
            action="DescribeTrails",
            version="2020-07-06",
            resource_type="Trails",
            result_path=("TrailList",),
            pagination="none",
        ),
    ],
    "ebs": [
        AliyunOperation(
            name="DescribeDedicatedBlockStorageClusters",
            action="DescribeDedicatedBlockStorageClusters",
            version="2021-07-30",
            resource_type="DedicatedBlockStorageClusters",
            result_path=("DedicatedBlockStorageClusters", "Dbsc"),
            pagination="token",
            page_size=50,
        ),
    ],
    "eci": [
        AliyunOperation(
            name="DescribeContainerGroups",
            action="DescribeContainerGroups",
            version="2018-08-08",
            resource_type="ContainerGroups",
            result_path=("ContainerGroups",),
            pagination="token",
            page_size=20,
            limit_param="Limit",
        ),
    ],
    "ros": [
        AliyunOperation(
            name="ListStacks",
            action="ListStacks",
            version="2019-09-10",
            resource_type="Stacks",
            result_path=("Stacks", "Stack"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListStackGroups",
            action="ListStackGroups",
            version="2019-09-10",
            resource_type="StackGroups",
            result_path=("StackGroups", "StackGroup"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListTemplates",
            action="ListTemplates",
            version="2019-09-10",
            resource_type="Templates",
            result_path=("Templates", "Template"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListResourceTypes",
            action="ListResourceTypes",
            version="2019-09-10",
            resource_type="ResourceTypes",
            result_path=("ResourceTypes", "ResourceType"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListResourceTypeVersions",
            action="ListResourceTypeVersions",
            version="2019-09-10",
            resource_type="ResourceTypeVersions",
            result_path=("ResourceTypeVersions", "ResourceTypeVersion"),
            page_size=50,
        ),
        AliyunOperation(
            name="ListResourceTypeRegistrations",
            action="ListResourceTypeRegistrations",
            version="2019-09-10",
            resource_type="ResourceTypeRegistrations",
            result_path=("ResourceTypeRegistrations", "ResourceTypeRegistration"),
            page_size=50,
        ),
    ],
}


def get_services():
    return sorted(ALIYUN_OPERATIONS.keys())


def get_operations(service):
    return ALIYUN_OPERATIONS.get(service, [])


def get_service_spec(service):
    return SERVICE_SPECS.get(service)
