# Mapping of Aliyun service short codes to human-friendly service names
# Generated from user-provided comprehensive list.
ALIYUN_SERVICE_NAMES = {
    'actiontrail': 'ActionTrail',
    'adb': 'AnalyticDB for MySQL',
    'adcp': 'Alibaba Cloud Distributed Cloud Container Platform',
    'aiworkspace': 'Platform for Artificial Intelligence PAI - AIWorkspace',
    'alb': 'Application Load Balancer',
    'alidns': 'Cloud DNS',
    'alikafka': 'ApsaraMQ for Kafka',
    'amqp-open': 'MQ for RabbitMQ',
    'apig': 'Cloud Native API Gateway',
    'arms': 'Application Real-Time Monitoring Service',
    'bssopenapi': 'Alibaba Cloud Billing',
    'cas': 'Certificate Management Service (Original SSL Certificate)',
    'cbn': 'Cloud Enterprise Network',
    'ccc': 'Cloud Call Center',
    'cdn': 'CDN',
    'chatbot': 'beebot',
    'clickhouse': 'ApsaraDB for ClickHouse',
    'cloud-siem': 'Security Center',
    'cloudapi': 'API Gateway',
    'cloudauth': 'ID Verification',
    'cloudfw': 'Cloud Firewall',
    'cloudsso': 'Cloud SSO',
    'cms': 'Cloud Monitor',
    'computenest': 'Computing Nest',
    'computenestsupplier': 'Compute Nest - Supplier',
    'config': 'Cloud Config',
    'cr': 'Container Registry',
    'cs': 'Container Service for Kubernetes',
    'csas': 'Secure Access Service Edge',
    'das': 'Database Autonomy Service',
    'dataworks-public': 'DataWorks',
    'dbs': 'Data Disaster Recovery',
    'dcdn': 'Dynamic Route for CDN',
    'ddosbgp': 'Protection Package',
    'ddoscoo': 'BGP-line Anti-DDoS Pro',
    'ddosdiversion': 'Anti-DDoS Diversion',
    'dds': 'ApsaraDB for MongoDB',
    'devops': 'Devops 2020',
    'dm': 'DirectMail',
    'dms-dg': 'DataManage - DatabaseGateway',
    'dms-enterprise': 'Data Management',
    'domain': 'Domain',
    'drds': 'Distributed Relational Database Service',
    'dts': 'Data Transmission',
    'eais': 'Elastic Accelerated Computing Instances',
    'eas': 'Elastic Algorithm Service',
    'ebs': 'Elastic Block Storage',
    'eci': 'Elastic Container Instance',
    'ecs': 'Elastic Compute Service',
    'edas': 'Enterprise Distributed Application Service',
    'eflo': 'Intelligent Computing LINGJUN',
    'eflo-cnp': 'Cloud Native Application Performance Optimizer',
    'eflo-controller': 'Lingjun-Controller',
    'ehpc': 'Elastic High Performance Computing',
    'ehpcinstant': 'E-HPC Instant Computing Service',
    'eiam': 'Identity as a service',
    'eipanycast': 'Anycast EIP',
    'elasticsearch': 'Elasticsearch',
    'emr': 'E-MapReduce',
    'energyexpertexternal': 'Energy Expert',
    'ens': 'edge node service',
    'esa': 'Edge Security Acceleration',
    'ess': 'Auto Scaling',
    'eventbridge': 'EventBridge',
    'expressconnectrouter': 'Express Connect Router',
    'facebody': 'viapi-facebody',
    'fc': 'Function Compute 3.0',
    'fc-open': 'Function Compute',
    'fnf': 'CloudFlow',
    'foasconsole': 'Realtime Compute Selling Console',
    'ga': 'Global Acceleration',
    'goodstech': 'viapi-goodstech',
    'gpdb': 'AnalyticDB for PostgreSQL',
    'green': 'Content Moderation',
    'gwlb': 'Gateway Load Balancer',
    'hbase': 'ApsaraDB for HBase',
    'hbr': 'Cloud Backup',
    'hitsdb': 'ApsaraDB for Lindorm',
    'hologram': 'Hologres',
    'httpdns': 'HttpDNS',
    'iacservice': 'Iac Service',
    'imageaudit': 'viapi-imageaudit',
    'imageenhan': 'viapi-imageenhan',
    'imagerecog': 'viapi-imagerecog',
    'imageseg': 'viapi-imageseg',
    'imm': 'Intelligent Media Management',
    'ims': 'RAM Identity Management Service',
    'iot': 'IoT Platform',
    'iqs': 'Information Query Service',
    'kms': 'KeyManagementService',
    'live': 'ApsaraVideo Live',
    'maxcompute': 'MaxCompute',
    'mse': 'Microservice Engine',
    'mssp': 'mssp',
    'mts': 'ApsaraVideo for Media Processing',
    'nas': 'File Storage NAS',
    'nlb': 'Network Load Balancer',
    'objectdet': 'viapi-objectdet',
    'oceanbasepro': 'ApsaraDB for OceanBase',
    'ocr': 'viapi-ocr',
    'ons': 'ApsaraMQ for RocketMQ 4.0',
    'onsmqtt': 'Light Message Queue MQTT',
    'oos': 'CloudOps Orchestration Service',
    'openapiexplorer': 'OpenAPI Portal Services',
    'openitag': 'ITag',
    'ossadmin': 'Object Storage Service Admin',
    'pai-dlc': 'Platform for Artificial Intelligence PAI - Deep Learning Containers (DLC)',
    'pai-dsw': 'Platform for Artificial Intelligence PAI - Data Science Workshop (DSW)',
    'paiautoml': 'Platform for Artificial Intelligence PAI - AutoML',
    'paielasticdatasetaccelerator': 'Platform for Artificial Intelligence PAI - DatasetAcc',
    'paifeaturestore': 'Platform for Artificial Intelligence PAI - Feature Store',
    'paiflow': 'Platform for Artificial Intelligence PAI - PAIFlow',
    'paillmtrace': 'PAI LLM tracing & evaluation',
    'paiplugin': 'Platform for Artificial Intelligence PAI - User Growth',
    'paistudio': 'Platform for AI',
    'polardb': 'ApsaraDB for POLARDB',
    'polardbx': 'Cloud Native Distribute Database',
    'privatelink': 'PrivateLink',
    'push': 'Alibaba Cloud Mobile Push',
    'pvtz': 'Alibaba Cloud DNS PrivateZone',
    'qualitycheck': 'Smart Conversation Analysis',
    'quotas': 'quotas',
    'r-kvstore': 'Tair (Redis® OSS-Compatible)',
    'rai': 'RAI',
    'ram': 'Resource Access Management',
    'rds': 'ApsaraDB for RDS',
    'resourcecenter': 'Resource Center',
    'resourcedirectorymaster': 'Resource Directory',
    'resourcemanager': 'Resource Management',
    'resourcesharing': 'Resource Sharing',
    'rocketmq': 'ApsaraMQ for RocketMQ 5.0',
    'ros': 'Resource Orchestration Service',
    'sae': 'Serverless App Engine',
    'saf': 'Fraud Detection',
    'sas': 'Security Center',
    'scdn': 'scdn',
    'schedulerx2': 'schedulerx',
    'sddp': 'Sensitive Data Discovery and Protection',
    'searchengine': 'SearchEngine',
    'servicemesh': 'Service Mesh',
    'sgw': 'Cloud Storage Gateway',
    'slb': 'Server Load Balancer',
    'sls': 'Simple Log Service',
    'smc': 'Server Migration Center',
    'sophonsoar': 'Security Center SOAR',
    'starrocks': 'EMR Serverless StarRocks',
    'sts': 'Security Token Service',
    'tag': 'Tag',
    'ververica': 'Realtime Compute for Apache Flink',
    'vod': 'ApsaraVideo VOD',
    'vpc': 'Virtual Private Cloud',
    'vpcipam': 'VPC IP Address Management',
    'vpcpeer': 'VPC peering connection',
    'waf-openapi': 'Web Application Firewall',
    'yundun-bastionhost': 'Bastionhost',
}
